### ISSUE TITLE
weird background colours

### ISSUE THREAD

**Issue by wayneashleyberry** [morhetz/gruvbox#101]
Hi :)

I'm getting very strange colours when I select text, is this supposed to happen?

Here are my settings:

```
syntax on
set background=dark
let g:gruvbox_italic=0
let g:gruvbox_contrast_dark='medium'
colorscheme gruvbox
```

MacVim:

![screen shot 2016-02-22 at 11 42 25 am](https://cloud.githubusercontent.com/assets/727262/13214631/823a5c0e-d959-11e5-8c42-c712701ebbc2.png)

Neovim:

![screen shot 2016-02-22 at 11 43 13 am](https://cloud.githubusercontent.com/assets/727262/13214626/7c86f916-d959-11e5-8054-fd3823b4a569.png)

**Comment by morhetz** [comment]
@wayneashleyberry 
Yep, there is an [option](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_invert_selection) to disable that behavior if you feel uncomfortable with that
```
let g:gruvbox_invert_selection=0
colo gruvbox
```

**Comment by wayneashleyberry** [comment]
Awesome, thanks @morhetz!
