### ISSUE TITLE
Hard to read error messages on gruvbox light

### ISSUE THREAD

**Issue by drzel** [morhetz/gruvbox#103]
It's pretty hard to read at the moment (neovim, 24-bit color, gruvbox light). I've fiddled around with some other values, but I'll leave that to you.
![gruvbox_red](https://cloud.githubusercontent.com/assets/8026227/13342032/d1b06f4a-dc91-11e5-8a04-f35b2202ea44.png)

**Comment by morhetz** [comment]
Thanks, fixed
