### ISSUE TITLE
Light bg colour not found in Readme

### ISSUE THREAD

**Issue by drzel** [morhetz/gruvbox#106]
I'm not sure why by my neovim bg colour when using default gruvbox light is #FDF4C1. This isn't found in the readme and meant I needed to adjust my terminal colour scheme for consistency.

**Comment by morhetz** [comment]
Please
1) [Read docs first](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#2-colors-are-off)
2) Attach screenshot
3) Describe your environment (term emulator, etc)

**Comment by drzel** [comment]
Yep, I checked the docs and the code. #FDF4C1 is used in the code, but not in the light mode palette image:

![Light Mode](https://camo.githubusercontent.com/a5a278806880562d3d205ac224103b55e8ae36d9/687474703a2f2f692e696d6775722e636f6d2f3439714b7959572e706e67)

**Comment by morhetz** [comment]
@drzel Whoops! Thanks got it. That's my fault.

**Comment by flyingfisch** [comment]
![screen](https://cloud.githubusercontent.com/assets/1307001/14005710/3638f72a-f13c-11e5-9d4c-5ea1aa2050cd.png)

Not sure if this is the same issue or not, but my background color doesn't seem to match the palette either. Gnome terminal 3.6.2, neovim 0.1.3-dev

**Comment by flyingfisch** [comment]
Just realized that I didn't have true color mode enabled, also found that my version of `gnome-terminal` does not have true color support. I am using `konsole` now, and the background color is much less bright.

@drzel are you sure you have true color support enabled? You can check by running `$ NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim`. If the colors look all off, then you don't have true color support in your terminal.

**Comment by morhetz** [comment]
@flyingfisch this issue is unrelated to the terms. drzel is totally correct.

**Comment by polyzen** [comment]
@morhetz, am I mistaken or does this mean the light bg is supposed to be #FDF4C1?

**Comment by morhetz** [comment]
@polyzen nope, that's legacy value being replaced by `fbf1c7`

**Comment by morhetz** [comment]
Doh, finally got this merged. Sorry, pals.
