### ISSUE TITLE
Different color for the number column?

### ISSUE THREAD

**Issue by ronakg** [morhetz/gruvbox#110]
Love this colorscheme except for this minor annoyance. The column (gutter) for the line numbers is not different from background. So it has tendency to merge with actual text.

Is it possible to provide an option for a darker/lighter color for this column?

**Comment by morhetz** [comment]
(`g:gruvbox_number_column`)[https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_number_column]
Done

**Comment by ronakg** [comment]
Thanks.

**Comment by aliceriot** [comment]
could you give an example of using this setting? I've been setting it to a variety of things but can't figure out how to use it properly.

**Comment by chriskaukis** [comment]
@aliceriot Try:

`let g:gruvbox_number_column='bg1'`

![screen shot 2017-06-30 at 10 38 18 am](https://user-images.githubusercontent.com/455/27743044-55fc7b0c-5d80-11e7-9234-547882f0aa69.png)
