### ISSUE TITLE
Problem with cursorcolumn and highlights

### ISSUE THREAD

**Issue by hamzadis** [morhetz/gruvbox#113]
Hi.

I've detected a few annoyances with this theme that happen when using `set cursorcolumn`. The first one happens when the column line intersects a search highlight. As you can see on the screenshot, the bg color of the line overrides the bg color of the highlight.

![screenshot from 2016-04-14 21-48-13](https://cloud.githubusercontent.com/assets/7688373/14541993/f7c20cf4-028c-11e6-94d2-7ec2624b1eb0.png)

The other, similar, but more annoying issue happens when using vim-easymotion. Again, when the column line covers a jump marker it is rendered almost invisible. This is especially bad when the cursor is on column 0, and one is using a motion that jumps to the start of the line. In this case, all the markers will be rendered illegible. Notice on this screenshot how the `l` and `v` markers are hard to spot.

![screenshot from 2016-04-14 21-49-14](https://cloud.githubusercontent.com/assets/7688373/14542135/a20fa48c-028d-11e6-8c6c-8c0801c52f0b.png)

It seems like the base16 themes had the [same issue](https://github.com/chriskempson/base16-vim/issues/39), not sure if that will help, though.

**Comment by morhetz** [comment]
Thanks for the feedback. This should be fixed now.
