### ISSUE TITLE
How to change VertSplit color?

### ISSUE THREAD

**Issue by monkoose** [morhetz/gruvbox#114]
Hello.
How i should change g:gruvbox_vert_split color in my config if you made `bg0, bg1, etc` variables as script variables? Did i miss something?
I still changed them just with `hi VertSplit guifg ...` in my config. But this question is still intresting for me.

**Comment by pmalek** [comment]
I have came across the very same problem. How did you solve this?

**Comment by pmalek** [comment]
Ok it seems that colors themselves are defined elsewhere. So, e.g.: 

```
let s:gb.dark0_hard  = ['#1d2021', 234]     " 29-32-33
```

is defined in `gruvbox/colors/gruvbox.vim` https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L89

I use it like:

```
let g:gruvbox_vert_split='dark0_hard'
```

**Comment by morhetz** [comment]
@pmalek Right. As wiki says it could be any color of gruvbox palette; either absolute one (`dark0`, `light4`) or relative (`bg0`, `fg4`)
