### ISSUE TITLE
Broken format specification for `strftime()' function in C

### ISSUE THREAD

**Issue by weezybusy** [morhetz/gruvbox#116]
![screenshot](https://cloud.githubusercontent.com/assets/9881220/15269849/b886cda0-1a14-11e6-9520-b8bc0a62298f.png)

**Comment by morhetz** [comment]
Unrelated to gruvbox
Refer to the filetype syntax highlighting
I personally use [this one](https://github.com/vim-jp/vim-cpp) though it reproduces same issue

**Comment by weezybusy** [comment]
Thanks, I'll try it out. No big deal, it doesn't annoy me too much.
