### ISSUE TITLE
comments are rendering incorrectly

### ISSUE THREAD

**Issue by pruett** [morhetz/gruvbox#118]
any idea why comments (and subsequently other highlight groups are rendering with like this?)

![screen shot 2016-06-12 at 10 25 16 pm](https://cloud.githubusercontent.com/assets/794809/15995645/b23ef014-30ec-11e6-9fe0-2f16b882c34a.png)

**Comment by morhetz** [comment]
@pruett yep, your term doesn't seem to [support italics](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#1-italics-is-disabled) so it renders it as inverted text instead.
You could totally disable italics with `let g:gruvbox_italic=1` at your vimrc to fix this.
Could you also provide details: your term emulator (or it's mvim/gvim), vim version, etc?

**Comment by pruett** [comment]
My apologies. Latest stable terminal vim on iTerm2 v3 beta. I think I was
using Monaco font. Thanks for the quick reply and fix.

**Comment by morhetz** [comment]
You're welcome.
By the way you could also try fixing italics support for the iterm though it could be tricky. Refer [Alex Pearce](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/) for the details

**Comment by pruett** [comment]
This looks super helpful. Thanks!
