### ISSUE TITLE
Italics not showing terminal vim

### ISSUE THREAD

**Issue by pruett** [morhetz/gruvbox#119]
As a followup to #118, I am using iTerm2 and have symlinked an updated ncurses repo to my terminfo

```bash
❯ brew install homebrew/dupes/ncurses

❯ brew link ncurses --force
```

Now my terminfo defaults to the ncurses folder

```bash
❯ infocmp $TERM
#	Reconstructed via infocmp from file: /usr/local/Cellar/ncurses/6.0_1/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
	el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
	rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>,
	rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m, rs1=\Ec,
	rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=,
	smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
	u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
	vpa=\E[%i%p1%dd,
```
As a result, I am able to see italics in the terminal

![screen shot 2016-06-15 at 3 31 34 pm](https://cloud.githubusercontent.com/assets/794809/16094450/4e8dab4a-330e-11e6-9f8d-c4dd50128665.png)

Unfortunately this is not the case for within terminal vim. I've set the italics flag to true in my `~/.vimrc`

```
let g:gruvbox_italic=1
```

Any ideas why italics aren't showing within vim?

**Comment by morhetz** [comment]
@pruett you're probably setting `g:gruvbox_italic=1` *after* `colorscheme gruvbox` which wouldn't work.
Just to be sure try running vim then at command-line:
`:let g:gruvbox_italic<CR>`
`:colo gruvbox`

**Comment by pruett** [comment]
i've tried setting it before and after, and setting it before actually obscures the colors...strange

**Comment by morhetz** [comment]
@pruett what do you mean by 'actually obscures the colors'? Could attach screenshot, please?

**Comment by pruett** [comment]
here's my current `.vimrc` that has proved the best results

```vim
"- Colors {{{
syntax enable " enbable syntax highlighting
set background=light " have Vim default to either light or dark setting
colorscheme gruvbox
let g:gruvbox_italic=1
let g:gruvbox_contrast_dark = 'soft'
" }}}
```

**when gruvbox_italic=1 is after colorscheme**
![screen shot 2016-06-15 at 4 09 14 pm](https://cloud.githubusercontent.com/assets/794809/16095672/b724c90e-3313-11e6-989c-9c46967647d7.png)

**when gruvbox_italic=1 is before colorscheme**
![screen shot 2016-06-15 at 4 10 18 pm](https://cloud.githubusercontent.com/assets/794809/16095676/bb86757e-3313-11e6-86a6-b56e7cd13efd.png)

I'm using my code-folded `.vimrc` because it has the most contrast

**Comment by morhetz** [comment]
@pruett ok, thanks!
Could you also provide the output of
`:set t_ZH`
`:set t_ZR`

**Comment by pruett** [comment]
`t_ZH=^[[7m`
`t_ZR=^[[m`

**Comment by morhetz** [comment]
@pruett seems like the cause of the issue. Fix it by putting next lines to your vimrc:
`set t_ZH=^[[3m`
`set t_ZR=^[[23m`

**Comment by morhetz** [comment]
Or if it's not working these lines instead:
`let &t_ZH="\e[3m"`
`let &t_ZR="\e[23m"`

**Comment by pruett** [comment]
that worked! are the t_ZH and t_ZR controlled by the colorscheme? just trying to figure out if it was something in my config. Thanks!

**Comment by morhetz** [comment]
Great!
Nope, that's something related to the terminfo–vim integration and colorscheme does nothing here.
So the issue is caused by vim which incorrectly detects italics escape codes from terminfo.

**Comment by pruett** [comment]
Thanks so much @morhetz I'll have to investigate if this is an issue with ncurses, all this seemed to pop up when I integrated it this morning

**Comment by morhetz** [comment]
Not at all. By the way you should try [neovim with true color support](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#0-recommended-nvim_tui_enable_true_color1) instead of the current setup; it looks awesome :)

**Comment by pruett** [comment]
i tried, but there was some incompatibility with neovim that i couldn't figure out, so i gave up 😦

**Comment by xrisk** [comment]
@morhetz I had this same issue which your custom escape codes fixed...Should this be filed as a bug in Vim? My .vimrc is very clean so I'm sure it's not the fault of any additional config.

BTW trying the test described [here](http://unix.stackexchange.com/q/228369/185354) in the question gives me the correct italics.

**Comment by wantyapps** [comment]
Hmm... this happens to me too, and nothing from the above fixes it... @morhetz can you help me?

**Comment by dougpagani** [comment]
@morhetz that isn't exactly correct... AFAIK, vim does not try to be smart and figure out what is the _italics_ escape code. It just sends a default one which may-or-may-not be interpreted as such by the receiving terminal. The terminal that vim runs in is the thing that needs to actually do "the stuff" for the italics. I just say this because it helps to understand the right context.

With that context in mind, for anyone arriving here for whom that is not the correct escape code (or, for a sanity check in order to make debugging easier), to figure out:
1. whether/how your terminal supports italics _at all_
2.  the right code without guessing
:
```
# sitm == set italics (print the ESC seq for)
# ritm == reset italics (print the ESC seq for)
$ tput sitm; echo test text; tput ritm

# Ok, if that worked, then just capture the output of tput so you know what the right ESC codes are:
$ tput sitm | less
```

This may not work if the terminfo database isn't configured correctly but... that's another layer I don't know anything about.
