### ISSUE TITLE
Python syntax highlighting keyword issue

### ISSUE THREAD

**Issue by Schabernack** [morhetz/gruvbox#125]
The current python syntax highlighting in vim emphasizes keywords if they are part of variable names. Other examples: list, print, map, None, in, ....

<img width="241" alt="screen shot 2016-08-07 at 1 09 43 am" src="https://cloud.githubusercontent.com/assets/155029/17460577/bb2b3e9c-5c3b-11e6-8f16-c95f2eed8479.png">

**Comment by morhetz** [comment]
That's problem with python syntax file. Unrelated to the gruvbox
