### ISSUE TITLE
Neovim update breaks gruvbox

### ISSUE THREAD

**Issue by maximsch2** [morhetz/gruvbox#128]
Gruvbox seems to rely on has('gui_running') which is no longer set by Neovim: https://github.com/neovim/neovim/wiki/Following-HEAD#20160204

**Comment by morhetz** [comment]
@maximsch2 It was reported before https://github.com/morhetz/gruvbox/issues/94
Gruvbox is not affected.

**Comment by maximsch2** [comment]
Yes, it looks like it was something weird on my end. I've ended up using neovim-qt which is not affected by terminal craziness, so all is good. Sorry for the noise.
