### ISSUE TITLE
Problems with italic and true-color

### ISSUE THREAD

**Issue by NovaDev94** [morhetz/gruvbox#133]
Hi guys,

I'm trying to have both italic works (for comments only) and truecolor support for `neovim`. And I have been able to achieve only "either" of them.  

For italic, I've followed this https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/, and everything goes well (even in tmux) `highlight Comment cterm=italic'.

The same goes for truecolor support with `set termguicolors` in the config file.  

However I realize that whenever I enable `termguicolors`, the italic won't work anymore. I'm using `hybrid` color-scheme so it doesn't have an option like `let g:gruvbox_italic` (but it still works if I disable `termguicolors`).  

Somehow `gruvbox` still works normally with `let g:gruvbox_italic=1`.

**Comment by morhetz** [comment]
Would you mind moving this issue to the vim-hybrid repo?
As it's totally unrelated to gruvbox if I got it rigth

**Comment by NovaDev94** [comment]
Sorry @morhetz... I just noticed that I posted it on the wrong repo...

**Comment by morhetz** [comment]
No problem at all
