### ISSUE TITLE
JavaScript colors do not match screenshot

### ISSUE THREAD

**Issue by adam-beck** [morhetz/gruvbox#136]
I know this is probably a sensitive issue because there are so many configurations and systems but I think I have a legitimate problem with the colorscheme.

I working on vim 7.4.2296 which supports truecolors. I have this set up so both my terminal and vim are capable of displaying truecolors. When I use ruby I can get the colors to match 100% accurately:

Mine:
https://imgur.com/a/9FCMa

Gallery: https://camo.githubusercontent.com/3a853e1f0c0774cb46c1f1ba0acf5633d2c21b3a/687474703a2f2f696d6775722e636f6d2f39794779456c5a2e706e67 

However, when I do the same in JavaScript:

Mine:
http://imgur.com/I97C4ju

Screenshot:
https://camo.githubusercontent.com/2fcf604967167347f15ca8be125d32b18db9bc28/687474703a2f2f692e696d6775722e636f6d2f476b496c38466e2e706e67

After running commands from [this gist](https://gist.github.com/XVilka/8346728) here are some of my outputs:

http://imgur.com/WJctFGy
http://imgur.com/eCTaqYX

Specs:
OS - Ubuntu 16.04
Terminal - GNOME Terminal 3.18.3 (Using VTE Version 0.42.5 +GNUTLS)
Tmux - 2.3
Vim - 7.4.2296
`tmux info | grep Tc` => `197: Tc: (flag) true`

I've tried disabling all of my vim plugins and only keeping gruvbox but that didn't seem to help. I assumed it was some syntax highlighter because it works in ruby but not in JS. Can somebody provide update screenshots for the Gallery for JavaScript? Maybe something has changed? 

Any ideas?

**Comment by morhetz** [comment]
I guess it depends on the js-syntax file
Original screenshot was taken with [yajs](https://github.com/othree/yajs.vim)
