### ISSUE TITLE
character bottom padding is twice top padding？

### ISSUE THREAD

**Issue by CNMan** [morhetz/gruvbox#139]
![2016-09-19_103634](https://cloud.githubusercontent.com/assets/8692234/18621501/dc855284-7e56-11e6-87a9-1783f3648387.png)
![2016-09-19_104933](https://cloud.githubusercontent.com/assets/8692234/18621505/f3fe2a12-7e56-11e6-9459-31c3913be42c.png)

gvim 8.0 x64 latest nightly build on windows server 2016 x64

**Comment by morhetz** [comment]
I'm totally sure that's unrelated to gruvbox and caused by incorrectly patched powerline font
Just to check: try both using unpatched font and disabling powerline symbols at airline

**Comment by CNMan** [comment]
Thanks.
not only the status bar and tab bar,but text area also have this problem.
I'll change the font to see if there is no problem.

**Comment by CNMan** [comment]
Fira Code have same issue
![2016-09-24_082840](https://cloud.githubusercontent.com/assets/8692234/18804692/2e1a2330-8231-11e6-8b1f-dea1bd30efd6.png)
vim itself have problem?
