### ISSUE TITLE
Orange Airline warning, even when there are no warnings

### ISSUE THREAD

**Issue by alexlafroscia** [morhetz/gruvbox#140]
I also see the corner of the Airline warning section, even if there are no warnings currently.

<img width="717" alt="screen shot 2016-09-19 at 6 56 58 pm" src="https://cloud.githubusercontent.com/assets/1645881/18655098/eb030cf4-7e9a-11e6-903e-8c3992f6afc3.png">

Is there a way to avoid this?  I've dug into the Airline docs a little bit, but I can't figure out how to control the color when there are no warnings present.  It doesn't make sense (or IMO, look good) to show that bright orange triangle even when there is no relevant warning information to show.

**Comment by morhetz** [comment]
`let g:airline_skip_empty_sections = 1` at your vimrc
https://github.com/vim-airline/vim-airline/pull/1130

**Comment by alexlafroscia** [comment]
You rock! Thanks for directing me to that.  It's been bugging me for months, had no idea there was a config option for it. It's amazing to me that that's not the default!

**Comment by morhetz** [comment]
@alexlafroscia no problem
