### ISSUE TITLE
Neovim terminal colors?

### ISSUE THREAD

**Issue by wayneashleyberry** [morhetz/gruvbox#144]
Adding support for neovim's terminal emulator would be awesome :)

onedark.vim does it here: https://github.com/joshdick/onedark.vim/blob/a0028d6e59c5a7192b49cbc6205dbb553f49d06c/colors/onedark.vim#L434-L457

**Comment by polyzen** [comment]
https://github.com/morhetz/gruvbox/wiki/Terminal-specific#0-recommended-neovimvim-true-color-support

**Comment by wayneashleyberry** [comment]
Oh cool, thanks for pointing out the pull request @polyzen - hopefully it'll be merged soon :)
