### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by BigfootN** [morhetz/gruvbox#152]
Hello,

I am trying to set the same background color in Neovim and in my terminal (urxvt 256 colors). The problem is that when trying to set my background color (from the colorscheme) : 
```
URxvt*background:  #32302f
```
I can see there is a difference with my terminal background color.

Here is my configuration:

```
" colorscheme
let g:gruvbox_contrast_dark = "soft"
set t_Co=256
set background=dark
colorscheme gruvbox
```
Thank you very much in advance

**Comment by dominiklohmann** [comment]
This should do the trick:

```
highlight Normal ctermbg=NONE
```

**Comment by BigfootN** [comment]
Wow, thank you very much !! 👍

**Comment by BigfootN** [comment]
Thank you very much, but when adding it to my _init.vim_ configuration the airline theme doesn't show the right colors. I have to source my _init.vim_ one more time, to have the right colors.

Thank you very much in advance

**Comment by morhetz** [comment]
@BigfootN 
> I am trying to set the same background color in Neovim and in my terminal (urxvt 256 colors). The problem is that when trying to set my background color (from the colorscheme)

Problem is the 256 colors palette. You could either use shell script or change or term bg color to mush degraded gruvbox palette

> the airline theme doesn't show the right colors

Could you please provide details and check with the airline maintainer?
Also possible dup https://github.com/morhetz/gruvbox/issues/108
