### ISSUE TITLE
markdown underline would got highlighted

### ISSUE THREAD

**Issue by huajie06** [morhetz/gruvbox#154]
Hi,

All the underline(_) would got highlighted which looks like region when writing markdown, is it because of my setting or it's kind of an issue?

Thanks,

**Comment by morhetz** [comment]
Could you please provide additional details like
* what's you markdown syntax plugin
* screenshot

**Comment by huajie06** [comment]
* I use the vim default setting
* screenshot
![capture](https://cloud.githubusercontent.com/assets/6091198/21668357/06dc3440-d2cf-11e6-8f74-8246cb1e097d.PNG)

It looks like it's only on headers and some bullet points

**Comment by morhetz** [comment]
@huajie06 
https://github.com/tpope/vim-markdown/issues/21

or switch to different md syntqax file
