### ISSUE TITLE
unknow function  gruvbox#bg_toggle

### ISSUE THREAD

**Issue by GianniGi** [morhetz/gruvbox#155]
If I press F5, I get this error
unknow function  gruvbox#bg_toggle

I added these to my vimrc:
map <silent> <F5> :call gruvbox#bg_toggle()<CR>
imap <silent> <F5> <ESC>:call gruvbox#bg_toggle()<CR>a
vmap <silent> <F5> <ESC>:call gruvbox#bg_toggle()<CR>gv

vim 8
windows 8.1

thanks :-)

**Comment by morhetz** [comment]
@GianniGi bg_toggle was deprecated 3yrs ago
delete these lines

**Comment by morhetz** [comment]
@glow12121 same as in 2012. Just bind it
