### ISSUE TITLE
Markdown Chinese

### ISSUE THREAD

**Issue by cconecode** [morhetz/gruvbox#156]
In Markdown, if I use Chinese, text would add underline, how can I fix it?
<img width="116" alt="qq20170103-0 2x" src="https://cloud.githubusercontent.com/assets/14048405/21601782/b7d217b8-d1c8-11e6-8d21-4c64d3512cb7.png">

**Comment by llinfeng** [comment]
把 下面的 設置 添加到你的 `.vimrc` 或者  `_vimrc`裏面就好了。

`set spell spelllang=en_us,cjk`

**Comment by cconecode** [comment]
已经解决了，非常感谢
