### ISSUE TITLE
Airline theme & highlight Normal ctermbg=NONE combination

### ISSUE THREAD

**Issue by synaptiko** [morhetz/gruvbox#160]
Hi,

I've started using ``highlight Normal ctermbg=NONE`` with gruvbox Airline theme recently. But I've noticed that if terminal is resized or if I call ``:AirlineRefresh`` manually then the color of the text of the mode is white instead of black.

It seems that if I replace every ``['Normal', 'bg']`` with ``['StatusLine', 'bg']`` it starts working and looks just ok even when I change it to `set :background=light` and back.

Would be there any trouble with such a replacement?

**Comment by morhetz** [comment]
duplicates #108
