### ISSUE TITLE
No contrast on light cursor color

### ISSUE THREAD

**Issue by mdsn** [morhetz/gruvbox#161]
When using the light background the cursor color is too light to see.

Vim 8.0, termguicolors on, tmux, st terminal

![contrast](https://cloud.githubusercontent.com/assets/1447384/22686257/253ff410-ed02-11e6-8d7c-870df1527a75.png)

**Comment by mdsn** [comment]
This was a terminal issue.

**Comment by gndowns** [comment]
@mdsn I am having the same issue using the Ubuntu default terminal. How did you fix it?

**Comment by fancsali** [comment]
> @mdsn I am having the same issue using the Ubuntu default terminal. How did you fix it?

Yes, please share the solution...

**Comment by mdsn** [comment]
@gndowns @fancsali by "terminal issue" i mean that the terminal emulator i was using (st) did not observe the cursor color. I didn't fix it as much as changed the cursor color to one that would stand out in both backgrounds.

**Comment by fancsali** [comment]
> @gndowns @fancsali by "terminal issue" i mean that the terminal emulator i was using (st) did not observe the cursor color. I didn't fix it as much as changed the cursor color to one that would stand out in both backgrounds.

I see. I literally thought, you've come up with some `.vimrc` tweaks that would adjust the cursor colour automatically. Apologies.

**Comment by eriknygren** [comment]
Just in case anyone else has this problem with iTerm2. I could resolve it by going into to `Settings -> Profiles -> Colors` and check _"Smart box cursor color"_:

![image](https://user-images.githubusercontent.com/5814512/66329841-211c2600-e927-11e9-8352-3fe99c7bce2d.png)
