### ISSUE TITLE
wrong color rendering in terminal mode

### ISSUE THREAD

**Issue by quentin-chen** [morhetz/gruvbox#168]
Using same configuration, but in the GUI mode `macvim` (above), the color scheme is correct, but in terminal mode `iTerm2/Terminal` (below), it's wrong:

![](https://ww1.sinaimg.cn/large/006tKfTcgy1feqswd1qe5j31a81bi122.jpg)

**Comment by morhetz** [comment]
https://github.com/morhetz/gruvbox/wiki/Terminal-specific
You're using 256-color pallete

**Comment by quentin-chen** [comment]
Once I used `set termguicolor` in vimrc:

![](http://ww2.sinaimg.cn/large/006tNc79gy1fesiqju16wj31040oagoe.jpg)

It's even worse.

**Comment by quentin-chen** [comment]
Solved by add gruvbox 256 color palette into `bashrc` or `zshrc`:

```
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
```
