### ISSUE TITLE
Strange `ff` characters with Neovim 0.2 on MacOS

### ISSUE THREAD

**Issue by ronakg** [morhetz/gruvbox#171]
I updated Neovim to 0.2 and now I'm seeing strange `ff` characters in the vim buffer when I do some operations like yanking etc. Same characters show up in command mode as well. (Check the screenshot)

It's easily reproducible. The issue goes away when I choose a different colorscheme. 

http://imgur.com/Qa5zLMi

There are no issues on my Ubuntu 16.04 machine. The issue occurs only on MacOS 10.12.4.

**Comment by albertorestifo** [comment]
I'm experiencing the same issue:

![](https://d26dzxoao6i3hh.cloudfront.net/items/310Z3h272i2L1u3r2p1A/Screen%20Recording%202017-08-01%20at%2010.29%20am.gif)

**Comment by morhetz** [comment]
@ronakg @albertorestifo 
https://github.com/neovim/neovim/issues/6584
