### ISSUE TITLE
g:gruvbox_contrast is deprecated; use g:gruvbox_contrast_light and  g:gruvbox_contrast_dark instead

### ISSUE THREAD

**Issue by Lalic** [morhetz/gruvbox#172]

**Comment by anianruoss** [comment]
Hey @morhetz I am trying to change the contrast using let g:gruvbox_contrast_dark=soft but I always get the error: 

Error detected while processing /home/anianruoss/.vimrc:
line   21:
E121: Undefined variable: soft
E15: Invalid expression: soft

Do you know what the problem could be?

**Comment by moon-musick** [comment]
@anianruoss `let g:gruvbox_contrast_dark='soft'`

**Comment by anianruoss** [comment]
@moon-musick awesome thanks!
