### ISSUE TITLE
Improve support for vim-sneak

### ISSUE THREAD

**Issue by ZzAntares** [morhetz/gruvbox#173]
Hello, first let me say that this colorscheme is awesome, I would say a drop in replacement for solarized, thanks for this!

However, I have a very small visual issue when using `vim-sneak`, in the readme says that it has integration with this plugin but when using the `s`nake feature I see a "_hideous magenta_" color that doesn't play nice with the gruvbox color palette:

<img width="204" alt="screen shot 2017-05-30 at 13 45 48" src="https://cloud.githubusercontent.com/assets/3653680/26599497/64f44d6a-453e-11e7-9271-5a0b56aebb50.png">

I think would be better to use the same color used in search highlighting in that case:

<img width="199" alt="screen shot 2017-05-30 at 13 46 06" src="https://cloud.githubusercontent.com/assets/3653680/26599518/7531dd14-453e-11e7-9c46-b34fb791271a.png">

Or some other color that fits nice with gruvbox.

Reading the `:help sneak` it says this colors can be changed, but which color exactly do I need to fit?

```vimscript
autocmd ColorScheme * hi Sneak guifg=black guibg=red ctermfg=black ctermbg=red
autocmd ColorScheme * hi SneakScope guifg=red guibg=yellow ctermfg=red ctermbg=yellow
```

Could you help me with this? More over, it will be nice that gruvbox came with a default highlight value for this sneak's highlight.

Thanks!

**Comment by morhetz** [comment]
Fixed
