### ISSUE TITLE
Whitespaces show as red while typing

### ISSUE THREAD

**Issue by bones97** [morhetz/gruvbox#174]
While typing after every <space> i enter i see red highlights, I have tried
everything i can possible think of, and find on the internet. I even installed
the [vim-better-whitespace](://github.com/ntpeters/vim-better-whitespace)' to
use the DisableWhitespace command, but to no avail.

**Comment by thriveth** [comment]
@bones97  Is this for all languages you write? Both text and code? I get the same behaviour in Python, but not in Markdown.

**Comment by bones97** [comment]
@thriveth  Y I see it only in python

**Comment by bones97** [comment]
Finally figured it out
adding this after colorscheme was set made the highlighting stop
````
autocmd $USER InsertEnter * syn clear EOLWS | syn match EOLWS excludenl /\s\+\%#\@!$/
autocmd $USER InsertLeave * syn clear EOLWS | syn match EOLWS excludenl /\s\+$/
highlight EOLWS ctermbg=red guibg=red
````
