### ISSUE TITLE
Official way to change terminal background color

### ISSUE THREAD

**Issue by Frefreak** [morhetz/gruvbox#176]
I want to make the background dimmer (darker) when using neovim inside tmux when the focus is lost, and change it back when the focus is gained. Currently I set autocommand to run `set g:gruvbox_contrast_dark=hard` followed by `color gruvbox` when `FocusLost`and set to `medium` when `FocusGained`. However I'm not satisified with the contrast between this two states. 234 (hard) is still a little too bright to me as a "dimmed" background.  If I try to execute `hi normal ctermbg=233` directly the color turns to a "light" theme. (I tested with only gruvbox installed so this is expected, right?)

What works for me is to add an option to `g:gruvbox_contrast_dark` similar to these two PR: https://github.com/morhetz/gruvbox/pull/165, https://github.com/morhetz/gruvbox/pull/102, one of them is rejected and the other is still opened. However the color in these two is not I want (I want colour 233 in my case).

 It would be nice to support this officially so users don't need to modify the plugin script directly. Maybe a user provided variable to set the fourth contrast option? Or what should be the way to just set the background color (and with the ability to change it back sometime later)

**Comment by Frefreak** [comment]
Turns out I was not using true color until just now... After enabling true color for both neovim and tmux the background can now be set directly using `highlight` command without problems. And it looks nicer than before.

So my problem is solved, but what if on a 256 color environment? IMO `highlight` should still just works...

**Comment by morhetz** [comment]
#135

**Comment by CHARLIEHEWSON11** [comment]
How do you put a color as your background, I’m confused?

**Comment by Frefreak** [comment]
@CHARLIEHEWSON11 `highlight normal guibg=#112233` if using gui or  with true color enabled. `ctermbg` if in terminal.
