### ISSUE TITLE
Would you  be okay, if we distribute this colorscheme with Vim?

### ISSUE THREAD

**Issue by chrisbra** [morhetz/gruvbox#180]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by morhetz** [comment]
@chrisbra Sure
Licensed under MIT/X11 feel free to do whatever you want to 😄

**Comment by chrisbra** [comment]
I can certainly do it. However, I won't be able to send updates, so I really would prefer if you would send the file (and again whenever an update is needed).

**Comment by morhetz** [comment]
@chrisbra Sorry, not my cup of tea. Plugin manager based approach is preferable to most power users. If you want to distribute gruvbox version and/or modification it's totally ok and up to you.
Currently I'm too lazy/don't have enough time to support gruvbox good enough (which I hope would change soon) and extra efforts on shipping it somewhere else wouldn't make it easier for me.
Sorry again.

**Comment by chrisbra** [comment]
okay, thanks. Send it to Bram/vim-dev for inclusion with Vim: https://groups.google.com/d/msg/vim_dev/_doeik3tbnQ/zrzVrN5-AgAJ

**Comment by wsdjeg** [comment]
I still prefer to use a plugin manager, using this github repo will be easy for issue report.

**Comment by chrisbra** [comment]
> I still prefer to use a plugin manager, using this github repo will be easy for issue report.

Nobody is preventing you to do this even in the future.
