### ISSUE TITLE
vim-airline broken after gruvbox update on Aug. 12

### ISSUE THREAD

**Issue by j5shi** [morhetz/gruvbox#188]
Vim-airline disappeared for inactive window, I didn't test which commit on Aug. 12 led to this as there were 19 commits on that day. BTW, I'm pretty sure it's the gruvbox that caused the issue as there's no such issue for other themes and problem solved after revert gruvbox back to previous commits.

## Before:
![before](https://user-images.githubusercontent.com/6829121/29393744-3a858a52-8338-11e7-920a-9cf94a9b3191.png)

## After:
![after](https://user-images.githubusercontent.com/6829121/29393747-3e8f91b0-8338-11e7-95de-75c4f86613fe.png)

**Comment by morhetz** [comment]
@j5shi That's vim airline theme issue
And as it's not the [gruvbox airline them port](https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim) there is nothing I could fix/care

**Comment by j5shi** [comment]
So I tested those commits one by one and found it's this commit that introduced the incompatibility. Maybe I should report this to vim-airline, thanks.

```
2017-08-12 07:07 Pavel Pertsev               o Adjust visual frames highlight 
```

**Comment by morhetz** [comment]
@j5shi not the airline but your specific airline theme

**Comment by j5shi** [comment]
@morhetz Ah yes, thanks for the reminder.

**Comment by morhetz** [comment]
@j5shi just fyi
<img width="1438" alt="vim" src="https://user-images.githubusercontent.com/554231/29414774-7dc60a18-8369-11e7-8404-c29868116b19.png">
gruvbox airline theme is working 👌

**Comment by j5shi** [comment]
That's wired...are you using the latest vim-airline? what airline theme are you using?

**Comment by morhetz** [comment]
@j5shi gruvbox airline theme
the one that [comes bundled](https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim) with the gruvbox colorscheme

**Comment by j5shi** [comment]
Holly shit, with this theme it works perfectly now, even cooler than the airline theme I used (`base16`) before. Thanks a million!!

![ok](https://user-images.githubusercontent.com/6829121/29415344-52a08486-8395-11e7-9986-6a3e3750b4a1.png)
