### ISSUE TITLE
conole.log() no longer colored.

### ISSUE THREAD

**Issue by danbruegge** [morhetz/gruvbox#189]
Hi, i've updated gruvbox today and found out, that `console.log` is no longer colored like the `super()` keyword. In the past it had that purple color.
![gruvbox-no-console-color](https://user-images.githubusercontent.com/1296438/29411834-b5796e68-8356-11e7-91b5-0f50cc3f3728.png)

Is that intended behavior or a mistake?

I use Archlinux with neovim in tmux within an xfce-terminal.

**Comment by morhetz** [comment]
@danbruegge 
`console`: intended behavior
`super` keyword: hm, missed that, need to think about

**Comment by danbruegge** [comment]
But these are reserved keywords. Why not show it?

**Comment by morhetz** [comment]
@danbruegge `console` is neither reserved nor keyword

**Comment by danbruegge** [comment]
Damn you're right. But why did you removed the color from the console? Now it looks strange and not like something that shouldn't be in the code besides testing or warning/error.

**Comment by morhetz** [comment]
@danbruegge 
`pangloss/js` syntax (which is polyglot base) counts console as `jsGlobalObjects` syngroup providing same one as `window`, `Promise`, `Array`, etc.
So there were too much coloring. Not the perfect solution but better then it was before. The idea is iterative enhancing of syntax coloring as syntax files are constantly changing too. Could come with a better ocloring later though it's pretty much ok for me at the moment.

**Comment by morhetz** [comment]
`super` is definitely the keyword, I'm just not sure about the color

**Comment by danbruegge** [comment]
Ok, then there is hope that it will gets back colored in the future. Maybe a light blueish one would be ok? So that is gets highlighted but does not distract the reading.
