### ISSUE TITLE
incorrect colors after switching colorscheme

### ISSUE THREAD

**Issue by rez-** [morhetz/gruvbox#192]
How to reproduce:
1. Open vi with colorscheme gruvbox, the colors are fine:
![image](https://user-images.githubusercontent.com/10398036/29712812-06b3c274-899c-11e7-8254-d7f932f4fa8d.png)
2. Switch to [solarized](https://github.com/altercation/vim-colors-solarized) colorscheme.
3. Switch back to gruvbox colorscheme, the colors are wrong:
![image](https://user-images.githubusercontent.com/10398036/29712822-111aa408-899c-11e7-9cd3-f7b635a8ba2d.png)

**Comment by morhetz** [comment]
@rez- https://github.com/altercation/solarized/issues/102#issuecomment-18109651

**Comment by rez-** [comment]
ah thanks for pointing that out to me :)
