### ISSUE TITLE
How did you make the color palette boxes?

### ISSUE THREAD

**Issue by NLKNguyen** [morhetz/gruvbox#193]
Hi there,

This looks nice, like a periodic table. Do you create this using a script? Can you please share the technique?

![](https://camo.githubusercontent.com/cdb2f2e986c564b515c0c698e6c45b4ab5d725a9/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67)

Thanks

**Comment by morhetz** [comment]
@NLKNguyen 
No sorry 😃 
I mean there is no script and it was made with sketch app
