### ISSUE TITLE
Cannot set colour of split line

### ISSUE THREAD

**Issue by mrded** [morhetz/gruvbox#196]
Hello,

After updating `gruvbox`, my split line lost a colour.

I use following settings in my `.vimrc`:
```
set background=dark

let g:gruvbox_vert_split='bg1'

" Delete pipe characters on styling vertical split borders
set fillchars+=vert:\ 
```
Once I open vim, split screen has no colour. 

![](https://i.imgur.com/BLVhkok.png)

If I do `:source $MYVIMRC` - colour of a split line gets back.
![](https://i.imgur.com/qQWKeUu.png)

I assume it's a `gruvbox` because it broke after I've updated it.

Please let me know if you need any more information.

**Comment by morhetz** [comment]
@mrded Hey
Seems like you're setting `g:gruvbox_vert_split` *after* calling `colo gruvbox`
And actually you need to do opposite
Gruvbox switched the default vertsplit bg, so that's why it got reset after updating

**Comment by mrded** [comment]
Right! it works now, thank you!

**Comment by morhetz** [comment]
🔥

**Comment by mrded** [comment]
Just for a record, a config must look like bellow:

```
let g:gruvbox_vert_split='bg1'

" Delete pipe characters on styling vertical split borders
set fillchars+=vert:\ 

colorscheme gruvbox
set background=dark
```
