### ISSUE TITLE
Better integration with Denite

### ISSUE THREAD

**Issue by ZzAntares** [morhetz/gruvbox#202]
Hello, I've been enjoying this theme for months now, it's so great!

However... I use [Denite](https://github.com/Shougo/denite.nvim) as a fuzzy finder, and when using it, the colors (or the way the results are matched) are quite unpleasant to the eye, here is what I mean:

<img width="455" alt="screen shot 2017-10-08 at 15 05 03" src="https://user-images.githubusercontent.com/3653680/31342999-ffab103a-acd3-11e7-8156-f74cc0b522fd.png">

Do you think this colorscheme could be responsible for customizing that? may be as a part of an integration? What I was thinking was that instead of changing the background color on the match would be better to change only the foreground color, or something along the lines to be more pleasant to look at it 😁 

Thanks for any help you can provide!

**Comment by peaceant** [comment]
You can set different highlighting with Denite option:

*denite-options-highlight-matched-char*
-highlight-matched-char
Matched characters highlight.
Default: "Search"

**Comment by ZzAntares** [comment]
Thanks, addig this options to Denite did the trick:

```
              \ 'highlight_matched_char' : 'Function',
              \ 'highlight_matched_range' : 'Function',
```
