### ISSUE TITLE
Override specific colors

### ISSUE THREAD

**Issue by isaachess** [morhetz/gruvbox#208]
It would be great to be able to override any specific color. This way you could define your own red, orange, etc., if a certain color (or all colors) do not quite suit your taste.

**Comment by foersben** [comment]
or it is not well highlighted like in .tex where parentheses and similar symbols are light pink and the text is white - I would like to replace the light pink by a darker pink or maybe orange

**Comment by morhetz** [comment]
@foersben `hi MyTexSyntaxGroup guifg=color ctermfg=color guibg=color ctermbg=color`
