### ISSUE TITLE
Configuration options do not work.

### ISSUE THREAD

**Issue by heartb1t** [morhetz/gruvbox#213]
I've set these options on my .vimrc:
`set background=dark`
`let g:gruvbox_italic = '1'`
`let g:gruvbox_contrast_dark = 'hard'`
`let g:gruvbox_color_column = 'bg1'`
`let g:gruvbox_italicize_comments = '1'`
`let g:gruvbox_invert_ident_guides = '1'`
`let g:gruvbox_improved_strings = '1'`
`let g:gruvbox_improved_warnings = '1'`

But it doesn't seem to change anything. Comments are not italicized, even though it is on the molokai colorscheme. I'm using terminal Vim on URxvt terminal emulator.

**Comment by morhetz** [comment]
Hey @heartb1t
Mind sharing vimrc?
I'd bet you're setting options after calling `colo gruvbox`
Also numbers shouldn't be stringified, so just
```
let g:gruvbox_italic = 1
```

**Comment by wsdjeg** [comment]
@heartb1t I think you should put this config before `colorscheme gruvbox`.

I recommand to use dein to manager your config, it support on_source feature, you can set a path for each plugin, then vim will load the config before loadding the plugin
