### ISSUE TITLE
Gnome-terminal profile

### ISSUE THREAD

**Issue by cbcoutinho** [morhetz/gruvbox#215]
I'm having trouble understanding/finding information on the following, so I apologize in advance if I've missed it.

I'm running `neovim` in `gnome-terminal` with `gruvbox` and everything works fine, and I would like to use the `gruvbox` colorscheme as the profile colorscheme associated with my _entire_ interactive shell. Is this possible and/or supported? I've tried sourcing the colorscheme shell file in my `~/.zshrc`, but that doesn't seem to do anything.

I'm having trouble finding conclusive answers to this question, because most of the issues I'm coming across are with other's (n)vim sessions in a gnome-terminal, and that's not the issue I'm having.

I would really appreciate any guidance regarding this, much appreciated.

**Comment by morhetz** [comment]
@cbcoutinho you should probably do two different things:
1) set up gnome-terminal color scheme. See [palette](https://github.com/morhetz/gruvbox-contrib#palette) and [color table](https://github.com/morhetz/gruvbox-contrib/blob/master/color.table) for details
2) set up vim color scheme, `termguicolors` on, no shellscript needed

**Comment by cbcoutinho** [comment]
Howdy @morhetz,

Thanks for the reply. I already have gruvbox working in both vim and neovim, that wasn't the issue. I was asking about the gnome-terminal profile itself.

I solved it by using the script found in the following repo: https://github.com/Mayccoll/Gogh
