### ISSUE TITLE
Cursorline for this theme

### ISSUE THREAD

**Issue by PezCoder** [morhetz/gruvbox#216]
I personally prefer having cursor line as it makes the tracking of the cursor easier, since the theme doesn't have any set by default.

I achieved that by using:
```vim
highlight CursorLine guibg=#3c3836
```

I chose the color matching the the background of CursorLineNr
<img width="714" alt="screen shot 2017-12-24 at 2 40 31 am" src="https://user-images.githubusercontent.com/8057916/34322666-d49a8aea-e853-11e7-9e94-7744bd6551f6.png">

Might be useful for other looking for something similar.

**Comment by morhetz** [comment]
You really shouldn't be doing this. Theme [does that](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L477) by default

<img width="389" alt="no name - nvim 2017-12-24 02-20-53" src="https://user-images.githubusercontent.com/554231/34323245-205a7d94-e851-11e7-849c-52d2e6f55395.png">

**Comment by PezCoder** [comment]
Ah, yes. I just realised that by just putting
`set cursorline` in vimrc it works.. Thanks for the tip.
