### ISSUE TITLE
Different style of Ubuntu 14 and 16

### ISSUE THREAD

**Issue by jonahfang** [morhetz/gruvbox#223]
I have two docker images based on ubuntu 14.04 and ubuntu 16.04,both use neovim+spacevim+gruvbox(in iterm2) , why they are different?

ubuntu 14.04
<img width="1369" alt="1404" src="https://user-images.githubusercontent.com/16301509/35256532-4f6c9dba-002f-11e8-9f45-d409a266e70a.png">

ubuntu 16.04
<img width="1433" alt="1604" src="https://user-images.githubusercontent.com/16301509/35256551-563f51d2-002f-11e8-9f39-9d1138efad4c.png">

**Comment by jonahfang** [comment]
I am using neovim inside tmux, when I remove tmux and run neovim alone, the two style became the same.

**Comment by morhetz** [comment]
@jonahfang no idea, sorry
looks like 14.04 is using solarized instead; it should be something with the spacevim
could you please open issue at spacevim repo?
