### ISSUE TITLE
How do you enable dark mode?

### ISSUE THREAD

**Issue by DrDonkey** [morhetz/gruvbox#224]
Installed gruvbox from aur, then put it in vimrc but it is light mode.
how do you change to dark mode.

**Comment by morhetz** [comment]
@DrDonkey `:set bg=dark`

**Comment by DrDonkey** [comment]
Thank you.

**Comment by acgtyrant** [comment]
The README and wiki does not mention how to enable the dark mode, you can add the explanation in them.

**Comment by reliefs** [comment]
How can i enable this in vimrc on auto.. i only get light mode

**Comment by DongshengHuang** [comment]
Thank you

**Comment by khoulyy** [comment]
Thank you
