### ISSUE TITLE
Konsole truecolor

### ISSUE THREAD

**Issue by jaspertravers** [morhetz/gruvbox#226]
I am using the Konsole Terminal Emulator with:
```
$TERM=xterm-256color
$COLORTERM=truecolor
```

I am following gruvbox's guide for terminal colors (https://github.com/morhetz/gruvbox/wiki/Terminal-specific) and read the TrueColour gist (https://gist.github.com/XVilka/8346728). When I run any of the print tests in Konsole they "pass" and I see appropriate colors.

My .vimrc has
```
set t_8f=^[[38;2;%lu;%lu;%lum
set t_8b=^[[48;2;%lu;%lu;%lum
set termguicolors
colorscheme gruvbox
```
(I correctly escaped the input `<C-V><ESC>` for `^[`  )
As suggested here (https://github.com/vim/vim/issues/993). 
My vim is not apropriately using truecolor and does not match the gallery shots.
How can I continue to debug this? I've gone through many forums and the above snippets are all I can find and issues were closed because they worked for others.

When I remove the `set termguicolors` line the view gets worse, with more faded colors and background - which suggests the set command is actually working there, but it doesn't go far enough, and there is still a faded view to the text and background which matches the description in the wiki for Terminal Specific issues. 

Thank you.

**Comment by nethershaw** [comment]
Why, after searching through "many forums," would you close your own issue without any explanation so that no one else can possibly learn from whatever it is that you found?
