### ISSUE TITLE
incorrect scss colors?

### ISSUE THREAD

**Issue by tylerfowle** [morhetz/gruvbox#227]
seems to be weird behavior with scss syntax.  not quite sure why the different types of propertys are different colors,  seems like they are kinda grouped into display/position, border, other, unknown.  Is this intentional?

but specifically ->
flex properties are white
`flex-direction` and `flex-wrap` are all white.
the color `black` isnt the same as other colors such as `red`, `white`, or variables `$green`

see attached screenshot.

![screen shot 2018-02-16 at 4 25 18 pm](https://user-images.githubusercontent.com/7574003/36332028-01b15cf4-1336-11e8-8905-a1802cbd683b.png)

**Comment by christianhegedues** [comment]
It seems you have an outdated css.vim syntax file and this cause the white flexbox properties. Try to update to a newer vim version, mine is 8.0.1700, and the flexbox properties should be fixed.

The different colors for some groups are defined in [gruvbox.vim](https://github.com/morhetz/gruvbox/blob/cb4e7a5643f7d2dd40e694bcbd28c4b89b185e86/colors/gruvbox.vim#L1026) and you can override them with putting the highlight group you want to modify after your colorscheme in your .vimrc

```vim
colorscheme gruvbox
highlight link cssPositioningProp GruvboxAqua
highlight link cssBorderProp GruvboxAqua
```
To get a list of all available highlight groups for a specific language take a look at the syntax file e.g. `/usr/local/Cellar/vim/8.0.1700/share/vim/vim80/syntax`, if you using homebrew

**Comment by tylerfowle** [comment]
im actually running Neovim v0.2.2

**Comment by tylerfowle** [comment]
I've installed https://github.com/JulesWang/css.vim and that seems to fix the issue
