### ISSUE TITLE
how install it on mac osx

### ISSUE THREAD

**Issue by xiangyuan** [morhetz/gruvbox#23]
how install it on mac osx

**Comment by Mardii-D-King** [comment]
When i Add Bundle 'morhetz/gruvbox' to your .vimrc and try to run :BundleInstall it tells me command not found. Could you please give me a more detailed step by step procedure, cause im new to all of this

**Comment by morhetz** [comment]
@Mardii-D-King it was changed to `Plugin` and `:PluginInstall`
Refer [wiki](https://github.com/morhetz/gruvbox/wiki/Installation) and [Vundle](https://github.com/VundleVim/Vundle.vim) for details

**Comment by nabn** [comment]
For me, the gruvbox shell script worked, but only for the current session (iterm 3.0.0).
i put it up on .zshrc to run the script on new terminal open

**Comment by morhetz** [comment]
@nabn That's exactly [what wiki suggests](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#a-256-color-gruvbox-palette-shellscript) to

> To avoid the necessity of reexecuting it each time you're opening terminal, you should start this script from .bashrc//.zshrc//.profile either

**Comment by nabn** [comment]
Haha.. my bad. didn't even see that there :)

On Mon, Jul 4, 2016 at 2:55 PM Pavel Pertsev <notifications@github.com>
wrote:

> @nabn <https://github.com/nabn> That's exactly what wiki suggests
> <https://github.com/morhetz/gruvbox/wiki/Terminal-specific#a-256-color-gruvbox-palette-shellscript>
> to
>
> To avoid the necessity of reexecuting it each time you're opening
> terminal, you should start this script from .bashrc//.zshrc//.profile either
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/morhetz/gruvbox/issues/23#issuecomment-230243123>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABnWZyIZ9YpK_f2qCP-i7ORlvoc_nQrjks5qSM37gaJpZM4BwmyL>
> .
>
-- 
- nabn
