### ISSUE TITLE
st and vim background colors mismatch

### ISSUE THREAD

**Issue by malikbenkirane** [morhetz/gruvbox#239]
Hey!

I'm using this great theme as my only theme but I like to switch between the three contrasts and the light and dark themes. I'm getting used to the manipulation and I will try to automate these. Typing `killall -s USR1 st` feels good to reset my settings while I'm already working.

This said, my minimal example is to get `st` and `vim`. The terminal emulator from suckless support True Colors for 256 bits and I fixed everything to work with the dark theme (thanks to the 256 colors script). Unless for the light theme the background seems wrong.

![screenshot](https://imgur.com/SobzIbJ.png)

Do someone figured out a way to fix this ? If so, the solution is welcome.

Best regards,

**Comment by malikbenkirane** [comment]
It seems that occurs when I change from the dark to the light theme and if I do not run `gruvbox_256palette.sh` script before launching vim. So I'm going to take this additional step in consideration if I want to automate switching themes across all my terminals
```sh
xrdb -override "/path/to/gruvbox-${theme}.xresources"
sh "/path/to/gruvbox/gruvbox_256palette.sh"
killall -USR1 st
```
This works on my side but the additional step should rather be sent by pipe for the changes to affect all already opened st terminals.

**Comment by morhetz** [comment]
Nice catch
Could you please also try [switching to `termguicolors`](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#2-colors-are-off)?

**Comment by malikbenkirane** [comment]
By now I catched your message,
It is `termguicolors` I'm using, but thank you.

Since then I have written some scripts, these need some cleaning but write vim commands to a file to source in my home directory so I can update colors nicely matching with terminal colors.
```vim

silence !sh "path/to/gruvbox/gruvbox_256palette.sh
let g:gruvbox_contrast_{light|dark}="{medium|soft|hard}"
colorscheme gruvbox
set bg={light|dark}

```

**Comment by giovannigiordano** [comment]
@morhetz I am facing the same issue after setting `termguicolors`
