### ISSUE TITLE
deal with tabs and spaces 

### ISSUE THREAD

**Issue by diboanches** [morhetz/gruvbox#248]
Hello! 

Where can I configure the number of spaces when go to next line? 
I am writing xml format file and when I press enter my new line is too far from the beginning, like that: 

<configuration>
               [cursor is here] 

This is too much.  Where to go to do something with it? :)

**Comment by morhetz** [comment]
@diboanches I beg your pardon,
1) as far as I understand this is totally unrelated to the gruvbox colorscheme
2) that depends on your vimrc and plugins
3) try `:h 'autoindent'` and check for filetype specific indent vim-files

**Comment by diboanches** [comment]
@morhetz oh, It is just never happened before I installed the gruvbox. 
Okay, I am going to take your advice, thank you.
