### ISSUE TITLE
gruvbox golang

### ISSUE THREAD

**Issue by lanox** [morhetz/gruvbox#254]
Hi, 

Are you still supporting this theme ?

I just wanted to ask you if something has changed in gruvbox theme for golang support, looking at the gallery for golang see below.

my system.
<img width="1032" alt="screen shot 2018-10-03 at 12 45 20 am" src="https://user-images.githubusercontent.com/7599183/46356365-f1986500-c6a5-11e8-824e-33db849150d4.png">

this is image from gallery you have posted.

![687474703a2f2f696d6775722e636f6d2f7535796e7264432e706e67](https://user-images.githubusercontent.com/7599183/46356391-0248db00-c6a6-11e8-98cc-08872e01d58b.png)

as you can see the imports are different color, just wondering is that normal, or are my colors screwed up.

Thanks

**Comment by idanko** [comment]
Hi, I suppose vim-go plugin has its own color binding which overrides a set vim theme. To prove it try to turn off the vim-go plugin and check the differences.

**Comment by gabrielbidula** [comment]
Same for me.
Using Alacritty and gruvbox vim without vim-go.
