### ISSUE TITLE
Feature request: Add support for vim-choosewin

### ISSUE THREAD

**Issue by greduan** [morhetz/gruvbox#26]
https://github.com/t9md/vim-choosewin

@morhetz Would be cool to have support for this plugin, because it's defaults are a bit ugly:

![2014-05-24-133106_1280x800_scrot](https://cloud.githubusercontent.com/assets/2314074/3075332/b160b580-e371-11e3-87c6-591d1228b77a.png)

Pay no mind to my WM, will Gruvbox it soon enough. :)

**Comment by morhetz** [comment]
Closing as this would probably never be done
