### ISSUE TITLE
Scrolling breaks gruvbox 

### ISSUE THREAD

**Issue by paulduf** [morhetz/gruvbox#267]
Hello

I have a bug with gruvbox when scrolling with my mouse in vim.

Below is the same file when I use first: my mouse scrolling and second: PageDown. Mouse scrolling fails to "trigger gruvbox" somehow but I can't be more precise since I'm newbie with vim programming.

Does anyone know how to fix this?

Thanks
![Screenshot from 2019-03-20 10-00-25](https://user-images.githubusercontent.com/27226228/54672049-8594a680-4af7-11e9-81ea-c6be398d6225.png)
![Screenshot from 2019-03-20 10-03-25](https://user-images.githubusercontent.com/27226228/54672053-86c5d380-4af7-11e9-8d84-2b9ee336a6de.png)

**Comment by rbong** [comment]
It appears to be a terminal-specific drawing issue. That looks like your background not being drawn over by Vim. Vim only redraws parts of the terminal window when it needs to and certain terminals can throw it off.

You could try a few different different things. If this is something that doesn't happen, the `:redraw!` command could clear it up. You could also set your terminal's background color to gruvbox's colors. Or, you could try a different terminal. This doesn't happen for me on alacritty, which is cross platform, so you may have luck with it.

**Comment by morhetz** [comment]
https://superuser.com/questions/457911/in-vim-background-color-changes-on-scrolling
