### ISSUE TITLE
Gruvbox alternatives

### ISSUE THREAD

**Issue by workgena** [morhetz/gruvbox#270]
Due to this statement:

> gruvbox is open source project
> I believe there are enough forks at the github and you're free to maintain your own
> As it's distributed under MIT license I feel like you have no restrictions to do so
> However gruvbox was started as a personal project and was maintained in my own tempo and according to my personal taste
> At the moment I think that adding maintainers is not what I would like to see
> No offence

_Originally posted by @morhetz in https://github.com/morhetz/gruvbox/pull/206#issuecomment-475966990_

Propose to collect alternative, actively maintained color schemes. And perhaps adding them to WiKi pages.

**Comment by workgena** [comment]
**Dark mode**

* https://github.com/ajmwagar/vim-deus
* https://github.com/srcery-colors/srcery-vim

**Light mode**

* ...

**Comment by morhetz** [comment]
I would sincerely ask you not to use gruvbox repo for the purpose of advertising other project
