### ISSUE TITLE
dark mode cursor not visible in OSX terminal

### ISSUE THREAD

**Issue by ian-atkinson** [morhetz/gruvbox#274]
Hi,

On OSX I have put

colorscheme gruvbox
set background=dark

into the vimrc, however when using the terminal version of vim the cursor is set to a very dark colour so is not visible. 

If I change to the light background I can see it as a very dark grey colour. My MacVim works fine however and in there the cursor seems to change to the colour of whatever it's currently over, or when it's not over text it's a light colour. In the terminal the cursor doesn't change colour.

Putting ':set termguicolors' in the vimrc does not help this as I saw suggested in another post.

Thanks,

Ian

**Comment by morhetz** [comment]
Setting cursor color is up to term emulator. Vim could set it at GUI mode only I believe
