### ISSUE TITLE
Gruvbox is broken in neovim

### ISSUE THREAD

**Issue by ChrisLee63** [morhetz/gruvbox#280]
When I open ~/.vimrc with Neovim
![image](https://user-images.githubusercontent.com/39628662/57563511-5270e400-73d1-11e9-9a69-ee6f48ede45e.png)
When I open ~/.vimrc with Vim
![image](https://user-images.githubusercontent.com/39628662/57563518-6e748580-73d1-11e9-918a-acdff627d3ef.png)
Gruvbox seems to be broken in neovim.
My config about scheme is as following:
```
set termguicolors
set background=dark                                                                                                                                              
let g:gruvbox_italic=1                                                                                                                                           
let g:gruvbox_contrast_dark='hard'                                                                                                                               
colorscheme gruvbox 
```
Can any one help on this?

**Comment by ronisbr** [comment]
It seems something similar to #260 

Unfortunately, it has been a long time since that issue was opened without any comments from the developer :(

**Comment by ppnman** [comment]
@ronisbr Thanks for your reply.
