### ISSUE TITLE
How to disable color of indent?

### ISSUE THREAD

**Issue by rivergold** [morhetz/gruvbox#283]
When I use gruvbox with python file, it always occurs light red color when I type indent or space.
![Selection_002](https://user-images.githubusercontent.com/6269549/58470880-390fbc00-8175-11e9-8ac2-09a7a0cbcc04.png)
How to disable the light red color of indent?

**Comment by rivergold** [comment]
It is not gruvbox error.
I solved it by add followings into `my_configs.vim`:

```vim
if exists('python_highlight_all')
    unlet python_highlight_all
endif
if exists('python_space_error_highlight')
    unlet python_space_error_highlight
endif
```

***Ref:*** [stackoverflow: How to stop Vim highlighting trailing whitespace in python files](https://stackoverflow.com/questions/47578780/how-to-stop-vim-highlighting-trailing-whitespace-in-python-files)

**Comment by Congstarrr** [comment]
> When I use gruvbox with python file, it always occurs light red color when I type indent or space. ![Selection_002](https://user-images.githubusercontent.com/6269549/58470880-390fbc00-8175-11e9-8ac2-09a7a0cbcc04.png) How to disable the light red color of indent?

May I ask which font and colour scheme you are/were using in this screenshot?
