### ISSUE TITLE
Background is too yellow

### ISSUE THREAD

**Issue by jlconlin** [morhetz/gruvbox#300]
I'm using gruvbox-light (installed via Vundle). However, the background feels much too yellow for what I was expecting. (See attached screenshot.)

The configuration I am using is:
```vim
colorscheme gruvbox
set background=light
let g:gruvbox_contrast_light="hard"
```

Please help me understand what I'm doing wrong. I love the plugin except for the harsh yellow.

<img width="1280" alt="Screen Shot 2019-10-01 at 12 55 05 PM" src="https://user-images.githubusercontent.com/1275437/65991541-c0827a00-e44a-11e9-9d01-23961b438431.png">

**Comment by asheidan** [comment]
Could this be related to (2) on this page?
https://github.com/morhetz/gruvbox/wiki/Terminal-specific

**Comment by jlconlin** [comment]
I had seen that wiki page. I'm using iTerm2 with a gruvbox light from gruvbox-contrib. I also have Vim 8.1.x. Not sure what other settings I need to make to get this right.

**Comment by morhetz** [comment]
That's something in between of Vim and iTerm. NeoVim works properly with the same iTerm version at the moment, while Vim drops to 256 co. Frankly speaking I have no idea what's wrong.

**Comment by morhetz** [comment]
Oh, and please be sure to have `set termguicolors`
