### ISSUE TITLE
Weird whitespace highlighting

### ISSUE THREAD

**Issue by Lucas-Pichette** [morhetz/gruvbox#304]
Hello! I love this colorscheme, but whenever I use the arrow keys to go up in my files the whitespace gets this interesting highlighting going on. Below will be my .vimrc file as well as an image of this issue.
![temp](https://user-images.githubusercontent.com/55814854/68727076-403a5300-0578-11ea-858e-b87eb5def90e.png)
![temp1](https://user-images.githubusercontent.com/55814854/68727083-43cdda00-0578-11ea-9609-0069c7e45598.png)

**Comment by Lucas-Pichette** [comment]
I resolved the issue by reinstalling the plugin using Vim-Plug as opposed to NeoBundle.

**Comment by arielgabizon** [comment]
Had same issue..also seems resolved by installing through Vim-Plug rather than Vundle
