### ISSUE TITLE
Sidebar highlighted color 

### ISSUE THREAD

**Issue by HenningCode** [morhetz/gruvbox#310]
Hey guys, 
do you Guys know how to get the part next to the number lines the same color as the background? It looks weird like this.

![image](https://user-images.githubusercontent.com/57907680/73598107-2899b780-4534-11ea-9819-de1266d6659f.png)

**Comment by morhetz** [comment]
https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_sign_column
