### ISSUE TITLE
Add to Wiki or Read.ME

### ISSUE THREAD

**Issue by jugheadjones10** [morhetz/gruvbox#312]
There's no mention of how to switch between dark mode and light mode; might be common knowledge for experts but for those new to vim it's a horrible experience trying to dig up obscure ways to do things...

**Comment by cfurrow** [comment]
Yeah, I agree. It's not a typical command to have to run day to day, in my opinion. I have no muscle memory for it.

```
" Set mode to "light"
set background=light

" Set mode to "dark"
set background=dark
```

**Comment by morhetz** [comment]
@jugheadjones10 
I'd gently argue against that. I'm not looking to turn this repo into vim 101 wiki.
Yes, 90% about vim is basically configuration hell and horrible user experience.
But not that specific issue in my opinion—in my opinion that's on of the easiest to google.

@cfurrow 
> I have no muscle memory for it.
Could I suggest you trying [`vim-unimpaired` by tpope](https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt#L78)?

**Comment by cfurrow** [comment]
I would gently argue the other way. It is completely unnecessary to require someone to google this when it could be so easy to show next to the screenshots you are already providing in your README.

Your suggesting googling, which would be this simulated experience, is better than 2 lines in a readme? I call shenanigans.

1. I see your plugin
2. I install it
3. It's light themed by default
4. I go back to the readme to see which config options I may have missed, none are found
5. I dig into the source of the plugin to figure out where I went wrong, and why the docs are missing this info
6. I realize it relies on `background` setting
7. I set the setting

Versus it just being in the readme. It's not turning your README into a "vim 101 wiki", that is a bad faith argument if I've ever read one. It's a common courtesy.

**Comment by morhetz** [comment]
@cfurrow 

> Your suggesting googling, which would be this simulated experience, is better than 2 lines in a readme? I call shenanigans.

Well first of all, one would never be able to set up vim without googling issues and reading vim docs. It is what it is. I have no intention to fix vim entry level / behavioral inconsistencies / terminal issues and what not. It's literally just a color scheme, not some kind of a framework.

> that is a bad faith argument if I've ever read one

Sorry for disappointing you.

I have been asked multiple times at gruvbox issues even on how to edit vimrc. I don't mind answering questions like that on my spare time but that's not the something I would like to expose to the readme or wiki.
