### ISSUE TITLE
Gruvbox is only showing a yellowish color

### ISSUE THREAD

**Issue by velazcorenier** [morhetz/gruvbox#315]
I'm trying to add gruvbox to my vim but is not showing the correct colors. This is like it look like <[example](https://imgur.com/8NMFLM7)>

**Comment by nodewiregit** [comment]
same here, even after editing .vimrc to include "let g:gruvbox_contrast_dark = medium". vim gives a warning that medium is not a legal variable. replacing it with a possible numeric value doesn't bring up the warning but doesn't change the colors either.

**Comment by nodewiregit** [comment]
#312 works however it still doesn't allow for the changing of contrast values.

**Comment by morhetz** [comment]
@velazcorenier there's no issue with that

@nodewiregit quote the value, `let g:gruvbox_contrast_dark = "medium"`
