### ISSUE TITLE
I got auto-transparent that don't expect after enable true color.

### ISSUE THREAD

**Issue by roachsinai** [morhetz/gruvbox#316]
I enabled true color by:

```
" https://lotabout.me/2018/true-color-for-tmux-and-vim/
if has("termguicolors")
    " fix true color not work under tmux
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    " enable true color
    set termguicolors
endif
```

It works for true color. But each time I use vim it enable transparent by it self.

![image](https://user-images.githubusercontent.com/9500049/75415633-29710e00-5967-11ea-8084-59574c659ab3.png)

If I remove that setting, the transparent effect disappear:

![image](https://user-images.githubusercontent.com/9500049/75415709-5ae9d980-5967-11ea-89bc-d06f15ddda59.png)

---

Expect behavior:

It should not be transparent on true color!

---

This doesn't happen when I change a color scheme, such as https://github.com/sainnhe/sonokai

**Comment by roachsinai** [comment]
https://github.com/vim/vim/issues/5703#issuecomment-591869868

**Comment by morhetz** [comment]
it doesn't seem to have anything to do with the colorscheme
