### ISSUE TITLE
let g:gruvbox_invert_selection=0 has no effect

### ISSUE THREAD

**Issue by yanzhang0219** [morhetz/gruvbox#317]
Hi,

I put this `let g:gruvbox_invert_selection=0` in my vimrc to disable the inverted color when making selections. It means that when I make some selections, the highlight will be uniform, right?
<img width="272" alt="image" src="https://user-images.githubusercontent.com/11582667/75605238-efeaf080-5a95-11ea-9063-91d11c08d90d.png">

But it has no effect. The selection still has inverted colors.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/11582667/75605253-07c27480-5a96-11ea-8409-286226b6a0fb.png">

Thanks.

**Comment by morhetz** [comment]
you should put it before `colo gruvbox`

**Comment by yanzhang0219** [comment]
Oh.. Thanks.
