### ISSUE TITLE
internal variable g:gruvbox_contrast_dark being overridden or not applying?

### ISSUE THREAD

**Issue by robbyjm** [morhetz/gruvbox#322]
hi, big fan of gruvbox. while working on my `.vimrc` i noticed that in order to apply `g:gruvbox_contrast_dark='soft'` I had to reload my `.vimrc` after starting vim. here's what my terminal looks like when i first start vim [https://imgur.com/a/aSZcypw](url) and here's what it looks like after reloading my .vimrc (`:so %`) [https://imgur.com/a/94yE7ll](url).

**Comment by jhhuisman** [comment]
I have the same issue FWIW.

**Comment by jhhuisman** [comment]
@robbyjm this works for me:
https://github.com/morhetz/gruvbox/issues/258#issuecomment-457215075

**Comment by robbyjm** [comment]
> @robbyjm this works for me:
> [#258 (comment)](https://github.com/morhetz/gruvbox/issues/258#issuecomment-457215075)

yup, worked for me too. thank you
