### ISSUE TITLE
Some colors are off for ruby

### ISSUE THREAD

**Issue by fladson** [morhetz/gruvbox#323]
Hey folks, I am not sure why but some keywords are off for me with ruby files.
I have tested this on multiple terminals, nvim and vim, outside tmux but I can't get the same colors seen on the screenshots.
![Screenshot from 2020-03-24 21-54-37](https://user-images.githubusercontent.com/554507/77476034-13495700-6e1a-11ea-8c56-fcf2d7e5f439.png)

`private` and `attr_reader` are some examples, they should be red.

On that screenshot I am using `nvim 0.4.3`, kitty terminal, outside tmux with a minimal config
```
Plug 'morhetz/gruvbox'
set termguicolors
colorscheme gruvbox
```

Any clue why?
Thank you

**Comment by megustalafantabienfria** [comment]
Same thing for elixir

It's weird, when I use vim 8.0 it looks nice but off for typescript. If I use vim 8.1 it looks off for elixir but for ts looks nice.

**Comment by r03** [comment]
Yes, Ruby looks a bit weird in Gruvbox

<img width="310" alt="image" src="https://user-images.githubusercontent.com/10061147/106311822-067d6700-6266-11eb-9548-596534ec466a.png">

I would expect 'def' to be red like 'func' in Go:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/10061147/106312089-6f64df00-6266-11eb-8d4e-e9891dbd7e85.png">

**Comment by joh-mue** [comment]
I have the same issue, unfortunately gruvbox8 doesn't seem to solve it and although lazyvim has treesitter by default, i still get the wrong colors for ruby. Has anyone found a solution for this?

**Comment by joh-mue** [comment]
And it might have stumbled upon a solution. I use lazyvim and just realised that treesitter did not have ruby language parser installed. I installed it with ":TSInstall ruby" and now everything looks proper. Hope it helps anybody else
