### ISSUE TITLE
gruvbox for sublime text 3

### ISSUE THREAD

**Issue by suchislife801** [morhetz/gruvbox#325]
Greetings.

The color harmony in this pallet is truly remarkable. Mind blowing. I was hoping you would consider implementing it in sublime text 3 as a dark theme. If there's anything I can do to help, feel free to reach out.

**Comment by suchislife801** [comment]
I have found a fork here on github.

[briles/gruvbox](https://github.com/briles/gruvbox)

**Comment by morhetz** [comment]
@suchislife801 
Yup, there're two Sublime themes that I'm aware of
https://github.com/morhetz/gruvbox-contrib#sublime--textmate

However I could say that I'm nor happy with the sublime adjustments neither with the vim always-in-flux color groups
