### ISSUE TITLE
HOW?

### ISSUE THREAD

**Issue by martinigoyanes** [morhetz/gruvbox#338]
I am relatively new to Vim, I have been using it for 4 months. I have a bunch of plugins enabled. However I can NOT make this airline statusline to work like I want.
How can i get the same statusline as in this picture???

<img width="1430" alt="687474703a2f2f692e696d6775722e636f6d2f775251636555522e706e67" src="https://user-images.githubusercontent.com/58919465/83278888-939e8680-a1d4-11ea-8c36-cc07cfc54650.png">

Please help,
Thank you.

**Comment by dev-martin** [comment]
This is what i get
<img width="1440" alt="Screen Shot 2020-05-29 at 6 01 30 PM" src="https://user-images.githubusercontent.com/58919465/83280178-8da9a500-a1d6-11ea-9694-44c36a2c3c7b.png">

**Comment by dev-martin** [comment]
Yeah I figured out I dont need the vim-ariline-themes plugin. Thank you. However how do I add the git status/branch and the full path to the file?

This is my vimrc:
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
call plug#begin('~/.vim/plugged')

" File Explorer
Plug 'scrooloose/nerdtree'

" Autocompletition
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Fuzzy finder
Plug 'kien/ctrlp.vim'

" Language checker
Plug 'vim-syntastic/syntastic'

" Commenting chunks of code with ,cc
Plug 'preservim/nerdcommenter'

" To surround expressions
Plug 'tpope/vim-surround'

" Start menu for when vim . ?
Plug 'mhinz/vim-startify'

" Terminal for vim?
Plug 'gu-fan/simpleterm.vim'

" Color Theme
Plug 'morhetz/gruvbox'

" Status Line
Plug 'vim-airline/vim-airline'

" All of your Plugins must be added before the following line
call plug#end()
filetype plugin indent on    " required


syntax on
set autoindent
set relativenumber
set nocompatible
set splitright
set t_Co=256
set laststatus=2
set number 		    " Set line numbers
set ts=4 sw=4 		" Set correct tab spaces
let mapleader = ',' " Remapped leader key to ','
inoremap `  <Esc>   " Remapped Esc key yo '`'
nnoremap <Leader>t :Sshow<CR> " Remmap terminal to ,t

" Remap tab keys to switch between tabs w/,. or ,m
nnoremap <leader>. :tabnext<CR>
nnoremap <leader>m :tabprev<CR>

" Autocomplete when you put a (,{ or [ 
inoremap {<cr> {<cr>}
inoremap [<cr> [<cr>]
inoremap (<cr> (<cr>)

" Shortcutting split navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Auto scp into ENEE150 after write/save in VIM
autocmd BufWritePost *ENEE150/Homework/* !/Users/martin/uni/ENEE150/scripts/hw.sh %:p 
autocmd BufWritePost *ENEE150/quizzes/* !/Users/martin/uni/ENEE150/scripts/quizz.sh %:p 
autocmd BufWritePost *ENEE150/projects/* !/Users/martin/uni/ENEE150/scripts/project.sh %:p 

" Auto copy files to buffovflow container whenever I save 
autocmd BufWritePost */CMSC414/projects/buffer-overflow/* !/Users/martin/uni/CMSC414/projects/buffer-overflow/build.sh

" Whenever something gets splitted, it will be be show on the bottom half
set splitbelow

" Set correct terminal size so its not too big
set tws="20*0"

" Remap o and O so they dont go into insert mode automatically
nnoremap o o<Esc>
nnoremap O O<Esc>


" Plugins Confiurations

" Airline config
let g:airline_powerline_fonts = 1

" NERDTree config
noremap <Leader>n :NERDTreeToggle %<CR>
let NERDTreeChDirMode = 2
let NERDTreeShowHidden = 2
	" Make NERDTree die when vim dies
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" CtrlP config
let g:ctrlp_cache_dir = $HOME.'/.tmp/ctrlp'
let g:ctrlp_working_path_mode = 'c'
map <C-p> :CtrlP c<cr>

" Synstastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_enable_balloons = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 1

	"Turn off Nullable annoyin errors in C programs
let g:syntastic_quiet_messages = { "regex": ['Nullable','_Nonnull'] }

" Gruvbox config
colorscheme gruvbox

" CoC Confiuration Start

	" TextEdit might fail if hidden is not set.
	set hidden

	" Some servers have issues with backup files, see #649.
	set nobackup
	set nowritebackup

	" Give more space for displaying messages.
	set cmdheight=2

	" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
	" delays and poor user experience.
	set updatetime=300

	" Don't pass messages to |ins-completion-menu|.
	set shortmess+=c

	" Always show the signcolumn, otherwise it would shift the text each time
	" diagnostics appear/become resolved.
	if has("patch-8.1.1564")
	  " Recently vim can merge signcolumn and number column into one
	  set signcolumn=number
	else
	  set signcolumn=yes
	endif

	" Use tab for trigger completion with characters ahead and navigate.
	" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
	" other plugin before putting this into your config.
	inoremap <silent><expr> <TAB>
		  \ pumvisible() ? "\<C-n>" :
		  \ <SID>check_back_space() ? "\<TAB>" :
		  \ coc#refresh()
	inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

	function! s:check_back_space() abort
	  let col = col('.') - 1
	  return !col || getline('.')[col - 1]  =~# '\s'
	endfunction

	" Use <c-space> to trigger completion.
	inoremap <silent><expr> <c-space> coc#refresh()

	" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
	" position. Coc only does snippet and additional edit on confirm.
	" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
	if exists('*complete_info')
	  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
	else
	  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
	endif

	" Use `[g` and `]g` to navigate diagnostics
	nmap <silent> [g <Plug>(coc-diagnostic-prev)
	nmap <silent> ]g <Plug>(coc-diagnostic-next)

	" GoTo code navigation.
	nmap <silent> gd <Plug>(coc-definition)
	nmap <silent> gy <Plug>(coc-type-definition)
	nmap <silent> gi <Plug>(coc-implementation)
	nmap <silent> gr <Plug>(coc-references)

	" Use K to show documentation in preview window.
	nnoremap <silent> K :call <SID>show_documentation()<CR>

	function! s:show_documentation()
	  if (index(['vim','help'], &filetype) >= 0)
		execute 'h '.expand('<cword>')
	  else
		call CocAction('doHover')
	  endif
	endfunction

	" Highlight the symbol and its references when holding the cursor.
	autocmd CursorHold * silent call CocActionAsync('highlight')

	" Symbol renaming.
	nmap <leader>rn <Plug>(coc-rename)

	" Formatting selected code.
	xmap <leader>f  <Plug>(coc-format-selected)
	nmap <leader>f  <Plug>(coc-format-selected)

	augroup mygroup
	  autocmd!
	  " Setup formatexpr specified filetype(s).
	  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
	  " Update signature help on jump placeholder.
	  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
	augroup end

	" Applying codeAction to the selected region.
	" Example: `<leader>aap` for current paragraph
	xmap <leader>a  <Plug>(coc-codeaction-selected)
	nmap <leader>a  <Plug>(coc-codeaction-selected)

	" Remap keys for applying codeAction to the current buffer.
	nmap <leader>ac  <Plug>(coc-codeaction)
	" Apply AutoFix to problem on the current line.
	nmap <leader>qf  <Plug>(coc-fix-current)

	" Map function and class text objects
	" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
	xmap if <Plug>(coc-funcobj-i)
	omap if <Plug>(coc-funcobj-i)
	xmap af <Plug>(coc-funcobj-a)
	omap af <Plug>(coc-funcobj-a)
	xmap ic <Plug>(coc-classobj-i)
	omap ic <Plug>(coc-classobj-i)
	xmap ac <Plug>(coc-classobj-a)
	omap ac <Plug>(coc-classobj-a)

	" Use CTRL-S for selections ranges.
	" Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver
	nmap <silent> <C-s> <Plug>(coc-range-select)
	xmap <silent> <C-s> <Plug>(coc-range-select)

	" Add `:Format` command to format current buffer.
	command! -nargs=0 Format :call CocAction('format')

	" Add `:Fold` command to fold current buffer.
	command! -nargs=? Fold :call     CocAction('fold', <f-args>)

	" Add `:OR` command for organize imports of the current buffer.
	command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

	" Add (Neo)Vim's native statusline support.
	" NOTE: Please see `:h coc-status` for integrations with external plugins that
	" provide custom statusline: lightline.vim, vim-airline.
	set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

	" Mappings using CoCList:
	" Show all diagnostics.
	nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
	" Manage extensions.
	nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
	" Show commands.
	nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
	" Find symbol of current document.
	nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
	" Search workspace symbols.
	nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
	" Do default action for next item.
	nnoremap <silent> <space>j  :<C-u>CocNext<CR>
	" Do default action for previous item.
	nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
	" Resume latest coc list.
	nnoremap <silent> <space>p  :<C-u>CocListResume<CR>

" CoC Confiuration End

**Comment by jorgebef** [comment]
Sorry I was unable to reply for the past couple of days.

Are you using vim in the terminal?
Also, I guess you checked already, but I made this mistake at first:
Are you inside a git repo? I spent at least a couple of hours and realised that I wasn't in one the first time I tried lol

Also, are you using one of the patched fonts for Powerline?
https://github.com/powerline/fonts

Those are the two things that come to my mind and that I encountered, I hope they help (if you haven't solved it already yourself).

**Comment by saadparwaiz1** [comment]
Seems like you don't have a git plugin that works with airline try installing [vim-fugitive](https://github.com/tpope/vim-fugitive), also you might want to set termguicolors which I think should fix the statusline

**Comment by tjx666** [comment]
I dont't know why my status bar is transparent

<img width="810" alt="Snipaste_2020-09-18_04-56-36" src="https://user-images.githubusercontent.com/41773861/93528541-0fcbfe00-f96d-11ea-9268-7fcda7afe28f.png">

**Comment by tjx666** [comment]
Fix it by change this theme community version

**Comment by TENX-S** [comment]
I also got this problem. But I'm using a [GUI of neovim](https://github.com/Kethku/neovide)
<img width="1440" alt="Screen Shot 2020-10-07 at 5 07 51 PM" src="https://user-images.githubusercontent.com/40336192/95311112-c31a7980-08bf-11eb-8835-4dfda530ce4c.png">

Here's my `.vimrc` and `$HOME/.config/nvim/init.vim`
* .vimrc
```shell
set hidden
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=3
set mouse=a
set nu
set guifont=Fira\ Code\ Retina

execute pathogen#infect()
syntax on
filetype plugin indent on
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
call plug#end()


let g:NERDTreeWinPos = "right"
autocmd vimenter * NERDTree

let mapleader=','
inoremap jj <Esc>`^
```
* $HOME/.config/nvim/init.vim
```shell
autocmd vimenter * colorscheme gruvbox
set background=light
syntax enable
filetype plugin indent on

let g:neovide_cursor_vfx_mode = "railgun"

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

How can I fix it ? Thanks a lot!
