### ISSUE TITLE
gruvbox_256palette.sh doesn't work for Konsole

### ISSUE THREAD

**Issue by zaferot** [morhetz/gruvbox#35]
Hi,

The gruvbox_256palette.sh has no effect for Konsole. I have not found the reason yet.
Maybe it is related to this bug: 
https://bugs.kde.org/show_bug.cgi?id=231405
I played with the script a little bit, but did not get any good results.
Do you have any ideas?

**Comment by flying-sheep** [comment]
konsole can print text with true color escape sequences, but this is about redefining…?

can someone break down the escape sequence for me?

`\033]4;223;rgb:eb/db/b2\033\\`

umm. what is <kbd>ESC</kbd><kbd>]</kbd> for a start?

**Comment by flying-sheep** [comment]
this bug seems to be it: https://bugs.kde.org/show_bug.cgi?id=233991
