### ISSUE TITLE
Tags in html are not highlighted as in the screenshot

### ISSUE THREAD

**Issue by hrqmonteiro** [morhetz/gruvbox#374]
In the screenshots on the gallery, tags in html like `navbar` are highlighted differently than the others (is white on the picture)

![2020-12-26_22-25](https://user-images.githubusercontent.com/17055027/103162013-59788000-47c9-11eb-9548-f12ba2ef506a.png)

but this is not actually happening when i installed the theme:

![2020-12-26_22-26](https://user-images.githubusercontent.com/17055027/103162023-757c2180-47c9-11eb-8f97-3e2495bafaac.png)

Is there any config i'm missing?

**Comment by cube-p** [comment]
do you have `set termguicolors` in your .vimrc/init.vim?

**Comment by hrqmonteiro** [comment]
> do you have `set termguicolors` in your .vimrc/init.vim?

Yes.
That is not the problem.

**Comment by cube-p** [comment]
Can you share your vimrc / init.vim? if I do not find anything strange it is possible that it is a problem of the same scheme

**Comment by hrqmonteiro** [comment]
> Can you share your vimrc / init.vim? if I do not find anything strange it is possible that it is a problem of the same scheme

The problem is in the scheme. I made a minimal vim config, with no plugins activated and only installed gruvbox, and i started vim with it. Still different.

Are the colors like the screenshot to you? Also i looked at gruvbox.vim, and there's no `hi html*` section that colorizes only tags like `main`. That's why i opened the issue.

And i wanted it colorized like that, it looks fine.

**Comment by cube-p** [comment]
after creating an html file, if I color the <navbar> tag

![gvim2](https://user-images.githubusercontent.com/76640988/103233831-11ae4180-490c-11eb-9664-cdda105e9553.png)

**Comment by hrqmonteiro** [comment]
Well the navbar tag was already right here, the issue was with the "main". In the screenshots it is colored white, but in here it is not.

**Comment by hrqmonteiro** [comment]
I'll close cause i think this is some misconception or some visual tweak on the screenshots and is not getting solved, and that's okay.
