### ISSUE TITLE
vim-signature crashes when I use gruvbox

### ISSUE THREAD

**Issue by DavidEGx** [morhetz/gruvbox#38]
Not sure if gruvbox is guilty or vim-signature is :-/

Anyway given my vimrc:

```
...
Bundle 'kshenoy/vim-signature'
Bundle 'morhetz/gruvbox'
...
if !has("gui_running")
  let g:gruvbox_italic=0
endif
set t_Co=256 | set background=dark | colorscheme gruvbox
```

Whenever I create a new mark, like hitting `ma` in normal mode I get:

```
Error detected while processing function signature#Input..signature#mark#Toggle..signature#mark#Place..signature#sign#Place..signature#sign#RefreshLine:
line   20:
E121: Undefined variable: SignatureMarkText
```

Commenting  lines 664 and 665 in ~/.vim/bundle/gruvbox/colors/gruvbox.vim seem to fix the problem for me.

**Comment by wyne** [comment]
i'm still getting this error with gruvbox enabled

``` vim
Error detected while processing function signature#utils#Input..signature#mark#Toggle..<SNR>115_Place..signature#sign#Place..<SNR>114_RefreshLine..<SNR>114_EvaluateHL:
line    2:
E121: Undefined variable: SignatureMarkText
E15: Invalid expression: SignatureMarkText
```

gruvbox version: 3f228101cdd5ae818415c7ebbcb42078c2476ea3
vim-signature version: 85b22e21ad4276c54d557ac640e1d32b2b4e6b5e

**Comment by morhetz** [comment]
@wyne 
Please update both signature and gruvbox as this might be related to #109

**Comment by wyne** [comment]
There were some patches on vim-signature that helped as well: https://github.com/kshenoy/vim-signature/issues/109

Everything working normally now. Thanks!

**Comment by kshenoy** [comment]
Yep, the issue was completely on my side. Sorry for the confusion!
