### ISSUE TITLE
[Q] what font does gruvbox-dark-soft use?

### ISSUE THREAD

**Issue by B00bleaTea** [morhetz/gruvbox#394]
I've been trying to figure out what font this theme uses for several hours, but i can't, does anyone know? i tried monospace, barlow, etc. but nothing looked right

![image](https://user-images.githubusercontent.com/71613062/115176317-64c72280-a0bc-11eb-9fe0-8f3d6c9f6c98.png)

**Comment by tusharsingh09** [comment]
I think it's Fira Code

**Comment by TruncatedDinosour** [comment]
> I think it's Fira Code

Ngl I don't remember, I think I found it (the reason I closed the issue) but I don't need it anymore,
but big thanks for replying as somebody else might need it :)
