### ISSUE TITLE
g:gruvbox_bold does not seem to be working

### ISSUE THREAD

**Issue by earik87** [morhetz/gruvbox#399]
Hi! 

I cannot see any effect of `g:gruvbox_bold` variable. What is the range for this? I tried 4, 6, 10 and even 20 but could not see any difference in the script. Although, other variables (such as `g:gruvbox_contrast_dark`) are working fine.

My vimrc; 

```
autocmd vimenter * ++nested colorscheme gruvbox
set background=dark

let g:gruvbox_contrast_dark='dark'
let g:gruvbox_bold='10'
colorscheme gruvbox
```

**Comment by windvalley** [comment]
> Hi!
> 
> I cannot see any effect of `g:gruvbox_bold` variable. What is the range for this? I tried 4, 6, 10 and even 20 but could not see any difference in the script. Although, other variables (such as `g:gruvbox_contrast_dark`) are working fine.
> 
> My vimrc;
> 
> ```
> autocmd vimenter * ++nested colorscheme gruvbox
> set background=dark
> 
> let g:gruvbox_contrast_dark='dark'
> let g:gruvbox_bold='10'
> colorscheme gruvbox
> ```

`g:gruvbox_bold` has only two values, `0` or `1`, and default is `1`. 

`g:gruvbox_contrast_dark` has three values: `soft`, `medium` and `hard`. Default: `medium`.

See the wiki: https://github.com/morhetz/gruvbox/wiki/Configuration

**Comment by earik87** [comment]
Thanks! I have missed this information!
