### ISSUE TITLE
Terminal background goes from translucent to solid

### ISSUE THREAD

**Issue by snowhawk1** [morhetz/gruvbox#413]
When using Gruvbox in NeoVim, my terminal background, which is normally translucent, becomes solid. Screenshot below:

![20211229_20h00m31s_grim](https://user-images.githubusercontent.com/73956879/147710621-368eea7f-cf6a-418c-bcca-348048c021de.png)

If anyone can help that would be appreciated

Software:
Linux Distro - Arch Linux x86_64
Kernel - 5.15.11
Terminal - Alacritty 0.9.0
Vim - NeoVim 0.6.0

**Comment by snprajwal** [comment]
See #375

**Comment by snowhawk1** [comment]
> See #375

fixed, thank you
