### ISSUE TITLE
Shows up as one theme instead of light soft,light hard etc.

### ISSUE THREAD

**Issue by JamievanSluijs** [morhetz/gruvbox#426]
When using the EAP version of PhpStorm Gruvbox only shows up as one theme instead of all colours available like on the normal PhpStorm version.
![image](https://user-images.githubusercontent.com/60099626/172025582-52f86757-f575-46d7-b4d3-99bcc75bd0e9.png)

**Comment by Plloi** [comment]
The MyGruvbox theme's repo is here: https://github.com/xiaopihai7256/MyGruvbox

Looks like it only has the one variant, are you sure you're using the same theme plugin you had  in non-EAP?
