### ISSUE TITLE
Comments looking strange withing tmux

### ISSUE THREAD

**Issue by PaBLoX-CL** [morhetz/gruvbox#43]
Colors aren't working for me, can you tell me where the issue could be? I read #4, but it doesn't seem to solve the problem.

https://asciinema.org/a/15575

Tmux is running with `screen-256color`, I also tried with `screen-256color-bce` with no avail.

PS.- I actually see the italics, dunno why they can't be seen trough the screencast

**Comment by morhetz** [comment]
First of all I would like to thank you for detailed ascii-video.

This is pretty much complicated issue totally unrelated to gruvbox colorscheme. I would recommend you to refer [this reddit thread](https://www.reddit.com/r/vim/comments/24g8r8/italics_in_terminal_vim_and_tmux/) for possible workaround.
It's also known that for the simplest cases just putting these lines to your vimrc works perfect:
```VimL
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
```

**Comment by PaBLoX-CL** [comment]
Wow, it does work this those little changes! :D, I will read the reddit thread with more details later :). Thanks!

I know that there's no need to run the script :), I just did it to be explicit about when I was using it or not. Though it seems I kind of like more the colorscheme without it :P.

**Comment by morhetz** [comment]
@PaBLoX-CL 
I've started simple vim-terminal integration plugin that simplifies things a lot, you could check out. I have not documented it yet, though it's tiny and pretty self-explanatory
[vim-termitr](https://github.com/morhetz/vim-termitr)

**Comment by PaBLoX-CL** [comment]
@morhetz by mistake I just found your comment about vim-termitr!! (somehow my email swallowed it :P). I'm gonna check it asap.
