### ISSUE TITLE
'gruvbox_transparent_bg' has no effect

### ISSUE THREAD

**Issue by Maik93** [morhetz/gruvbox#439]
Hi, really nice theme!
I'm enjoying it a lot, there's only one thing that is left for me: I'd like to have the same background as the current shell.

I think that this should be handled by the variable `gruvbox_transparent_bg`, as stated in the wiki, but it seems to have no effect.
Searching for "gruvbox_transparent_bg" string on this repo, produces no results, so is this a feature that still needs to be implemented?

**Comment by Hjagu09** [comment]
there is an fix for this, #287

**Comment by Maik93** [comment]
Thanks, it seems that that pull request isn't merged neither in this repo or in [gruvbox-community](https://github.com/gruvbox-community/gruvbox).

**Comment by pm0u** [comment]
Anyone else looking, adding this to `.vimrc` worked for me:
```
hi Normal guibg=NONE ctermbg=NONE
```

source [here](https://stackoverflow.com/questions/37712730/set-vim-background-transparent)
