### ISSUE TITLE
How can i modify multiple comment scheme

### ISSUE THREAD

**Issue by arcticlion** [morhetz/gruvbox#46]
Look, it look terrible when multiple comment
![](http://ww1.sinaimg.cn/large/8178ba0ejw1eoxai8qh3oj21ds0waqan.jpg)

How can i modify multiple comment scheme to make more artistic?

**Comment by morhetz** [comment]
[Please, read wiki first](https://github.com/morhetz/gruvbox/wiki/Terminal-specific)

**Comment by arcticlion** [comment]
@morhetz Sorry, i configure my development according to wiki, but it doesn't change at all.

This is my dot file.
[.zshrc](https://gist.github.com/arcticlion/07959c1fd95240337a26)
[.bash_profile](https://gist.github.com/arcticlion/1b22ac4a5c40893442d3)
[.vimrc](https://gist.github.com/arcticlion/78a61b9042bdb5d8524f)

**Comment by morhetz** [comment]
Just swap these lines
```
 " Gruvbox Color Scheme for Vim
colorscheme gruvbox
let g:gruvbox_italic = 0 
```
to
```
 " Gruvbox Color Scheme for Vim
let g:gruvbox_italic = 0
colorscheme gruvbox
```

And I'm not so sure that `source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette_osx.sh"` at your zshrc is the correct path, since Vundle isn't mentioned at your `vimrc`

**Comment by arcticlion** [comment]
Thanks a lot. It display normal.

Could you ask me why succeed just swap two line?



在 2015年2月4日 下午5:31:52, Pavel Pertsev (notifications@github.com) 写到:

Reopened #46.

**Comment by morhetz** [comment]
Configuration options should be set *before* loading colorscheme, since gruvbox tries to parse config options on load and doesn't handle changes on the fly.
