### ISSUE TITLE
Unable to log in when sourcing the palette shellscript

### ISSUE THREAD

**Issue by sinapinto** [morhetz/gruvbox#48]
As mentioned in the wiki, I added the line `source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"` to my `~/.zshrc` and later noticed that this prevented me from logging in to this user (the .zshrc file gets sourced at login). 

I'm not sure what is causing this problem -- the file exists and has the needed permissions. However I made a modification to the line so it wouldn't get sourced at login, and I'm able to log in again.

`[[ -o login ]] || source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"`

**Comment by sinapinto** [comment]
upon further inspection it seems it was lines 80-82 in the shellscript that were causing the issue.

```sh
if [ "$TERM" = "linux" ] || [ "$TERM" = "vt100" ] || [ "$TERM" = "vt220" ]; then
    exit 1                                                                 
fi 
```

**Comment by morhetz** [comment]
Hmm, that's strange. Could you please specify your OS//WM?

**Comment by sinapinto** [comment]
I'm using 32-bit Arch linux with 3.18.6 kernel.  The problem is independent of the WM since it occurs outside of X. (and i'm not starting X automatically at login or anything).

I think what's happening is that at login, since my $TERM is "linux", the `exit 1` gets called and it immediately logs me out.  But I could be mistaken..
