### ISSUE TITLE
Italic font in terminal(urxvt)

### ISSUE THREAD

**Issue by zaferot** [morhetz/gruvbox#49]
Hello!

Recently you have disabled italics in terminals by default. How can I enable it again?
I use urxvt and I tried to add "let g:gruvbox_italic=1" in my .vimrc, but it did not help.

**Comment by morhetz** [comment]
You should try setting `let g:gruvbox_italic=1` _before_ `colo gruvbox`
Does it help?

**Comment by zaferot** [comment]
It helped. Thanks!
I guess it's worth to be mentioned in the wiki.

**Comment by morhetz** [comment]
Thanks. [Done](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#1-italics-is-disabled)
