### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by skywinder** [morhetz/gruvbox#54]
Hi. I use Vundle.
So, I add string:

    Plugin 'morhetz/gruvbox'

 change string 

    colorscheme badwolf

to: 

    colorscheme gruvbox

And run vundle installation `vim +PluginInstall +qall`
But I gets error:

> Not an editor command: colorcheme gruvbox

Also I try to delete colorscheme. But have no luck.
Also I try to add and remove

    set background=dark    " Setting dark mode

But it don't get any effect.

Whats I'm doing wrong?

**Comment by morhetz** [comment]
> Not an editor command: colorcheme gruvbox

I suppose it should be color**s**cheme

**Comment by skywinder** [comment]
Ouh.. Yes. Just a dummy typo. :beetle: 
Thanks - awesome scheme! :+1:
