### ISSUE TITLE
Request: change color of block quote in markdown

### ISSUE THREAD

**Issue by mclearc** [morhetz/gruvbox#57]
I'm wondering if you'd consider setting the color of block quotes in markdown to something other than the current grey? Right now this is the same color as footnote text (though not the identifier, which is a pleasant red). It would be nice to have these differentiated, and to have the block quotes in a brighter color, perhaps blue?

I use vim, and your excellent color scheme, primarily for writing, and this change would help me.

**Comment by morhetz** [comment]
Hi. What's your markdown plugin?
I wasn't planning to extrahighlight block quotes. Are there actual reasons to make them brighter?

**Comment by mclearc** [comment]
I use [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) for most of my markdown reading/writing. I'd be happy with differentiation if you would prefer not to make them brighter. I suggested that only because I tend to write things with a fair number of block quotes and the color differentiation keyed to something brighter helps me scan through and find them more easily. I don't know if that's enough reason  for you to make the change.

**Comment by mclearc** [comment]
I'm not using vim-pandoc anymore, so I'll close this issue.
