### ISSUE TITLE
option to disable the color settings for Indent Guides

### ISSUE THREAD

**Issue by BimbaLaszlo** [morhetz/gruvbox#58]
I'm using the [Indent Guides](https://github.com/nathanaelkane/vim-indent-guides) plugin, but the Gruvbox disables the color setting for it. It may be good to have an option to disable this behaviour, because if the indent char is space, then the visual mode's color is the same as the indenting color and it can be frustrating when i like to select the indent itself for example.

![indent with spaces](https://cloud.githubusercontent.com/assets/7034200/7596292/edb3e854-f8ec-11e4-9bd5-9c35722e9917.png)

![indent with tabs](https://cloud.githubusercontent.com/assets/7034200/7596344/3f81a6e4-f8ed-11e4-966d-b188563f4485.png)

**Comment by morhetz** [comment]
Not sure what's your problem.
> colo gruvbox
> hi IndentGuidesOdd  guibg=red   ctermbg=3
> hi IndentGuidesEven guibg=green ctermbg=4
Is this working for you?

**Comment by BimbaLaszlo** [comment]
It's works, so it can be a solution but it is not fine to set up the colors directly, because there is a `g:indent_guides_color_change_percent` which does the job for me. What i like to modify in Gruvbox is disabling [these lines](https://github.com/morhetz/gruvbox/blob/2480e488809d3686aeecea45582942ad6ec704fd/colors/gruvbox.vim#L593-L601) to let the variable do what is it for.

**Comment by morhetz** [comment]
update gruvbox from repo, so you could put `let g:indent_guides_auto_colors = 0` to your vimrc to fallback to default indent guides highlighting

**Comment by BimbaLaszlo** [comment]
Thanks! It works fine if `g:indent_guides_auto_colors = 1`. :)
