### ISSUE TITLE
Diff styles are not bold in terminal

### ISSUE THREAD

**Issue by sunaku** [morhetz/gruvbox#59]
How it looks right now (it's very hard to read on my monitor :eyeglasses:):
```vim
:hi DiffAdd
DiffAdd        xxx term=bold ctermfg=236 ctermbg=142 guifg=#32302f guibg=#b8bb26
Press ENTER or type command to continue
```
![selection_046](https://cloud.githubusercontent.com/assets/9863/7674194/ddb36464-fcd6-11e4-944c-91d9d5fa8919.png)

How it looks after manually running `:hi DiffAdd cterm=bold` command:
![selection_047](https://cloud.githubusercontent.com/assets/9863/7674193/ddae67b6-fcd6-11e4-8ddf-12acde1ee7be.png)

**Comment by morhetz** [comment]
I suppose most people wouldn't like diff text to be bold. Why don't you just override highlighting settings at your .vimrc?

**Comment by sunaku** [comment]
Ah yes I could do that, but I reported this issue because gruvbox's DiffAdd style _already_ specifies `term=bold` which isn't having any effect under xterm-256color for me. :sweat_smile:  If we prepend a single `c` character to that `term=bold` specification, making it `cterm=bold`, the problem is fixed on my system.

**Comment by morhetz** [comment]
@sunaku I'm sorry I didn't pay much attention to your `hi DiffAdd` output.
If you'll take a look at gruvbox's sources it does nothing to `term` highlighting, specifying `cterm` and `gui` modes only, so `term=bold` could be default vim highlighting that was not overriden. To sum up neither gruvbox tries to make `DiffAdd` embolden nor it has anything to do with pure `term`.

**Comment by sunaku** [comment]
Thanks for the tip!  You're right, that bold comes from Vim itself:

```sh
$ vim -u NONE -c 'hi DiffAdd'
DiffAdd        xxx term=bold ctermbg=81 guibg=LightBlue
Press ENTER or type command to continue
```

So there's nothing more to be done here.  Closing! :sweat_smile:
