### ISSUE TITLE
JavaScript: Color keyword new.

### ISSUE THREAD

**Issue by MeanEYE** [morhetz/gruvbox#61]
As you can see on screen shot below all keywords such as `self`, `var`, `if`, etc. are colored the same way except for `new`. Since `new` is also a keyword it should be, in my opinion, colored the same way.

![2015-05-27-151106_569x332_scrot](https://cloud.githubusercontent.com/assets/1911594/7836707/9d453444-0482-11e5-9b8c-e3c41c389691.png)

Thanks!

**Comment by MeanEYE** [comment]
I realized this is by design and also saw PR. No need to build this. It makes sense why it's not colored. Thanks!

**Comment by morhetz** [comment]
For anyone who cares, gruvbox now supports yajs.vim which highlights `new` keyword properly
![1](https://monosnap.com/file/3I7nHxyG8YLcHKmf6kiRRziSA7W98n.png)

**Comment by MeanEYE** [comment]
Thanks!
