### ISSUE TITLE
listchar color changes with cursorline

### ISSUE THREAD

**Issue by amfl** [morhetz/gruvbox#62]
* Expected: Listchars (`$` at end of line in example) to be the same color for all lines
* Experienced: Listchars turn normal text color on cursorline lines.

Reproducable with this .vimrc and vim-plug:

```vim
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

set background=dark
colorscheme gruvbox

set cursorline
set listchars=eol:$
set list
```

Image:

![Image](http://puu.sh/i4olh/99bc217e8a.png)

This may be related to issue #40 ?

Although this might actually be intended behavior :)

**Comment by morhetz** [comment]
It's side effect which currently is also an intended behaviour
You could always change eol listchar, if it's misleading (I prefer negation symbol `¬`)
