### ISSUE TITLE
Comments not highlighted in Clojure source code

### ISSUE THREAD

**Issue by cassiomarques** [morhetz/gruvbox#63]
Hi,

When editing Clojure files using this colorscheme, comments are not properly highlighted. Basically the code inside a comment block is highlighted as if it were just normal code.

![screen shot 2015-06-04 at 21 28 47](https://cloud.githubusercontent.com/assets/13071/7993809/bac9b0e2-0b00-11e5-8959-300c13cd7e8e.png)

Thanks!

**Comment by ShengYun** [comment]
Can you please post the file online so I can test? I tried to clone some random clojure code and the comments seems correct.

**Comment by cassiomarques** [comment]
@ShengYun sorry for the late reply.

This happens with any Clojure file I try to edit.

Are you aware of any settings in my .vimrc or other plugins that could cause this problem with the colorscheme?

Thanks!

**Comment by ShengYun** [comment]
@cassiomarques I don't know how to write Clojure, but I tried to download a few Clojure files and the comments seems correct, maybe try to disable all other plugins and enable them one by one? or check  your vimrc?

**Comment by cassiomarques** [comment]
@ShengYun I was able to isolate the problem to https://github.com/luochen1990/rainbow plugin. I was using an older version that was causing the problem described before. Now I updated the plugin and I am having a different problem, comments are displayed with a grey background:

<img width="240" alt="screen shot 2015-07-04 at 17 30 42" src="https://cloud.githubusercontent.com/assets/13071/8508701/7069ca80-2272-11e5-9b7c-fa8404c1b6d6.png">

Thanks for any help!

**Comment by morhetz** [comment]
@cassiomarques That's probably happening cause you've enabled `g:gruvbox_italic=1` at the term
Could you show your .vimrc please?

**Comment by cassiomarques** [comment]
@morhetz here it is https://gist.github.com/cassiomarques/bbcf160ccb42b5858216

I had a look and it does not look like I am enabling `g:gruvbox_italic=1` tough, at least not directly. 

Thanks!

**Comment by morhetz** [comment]
@cassiomarques could you update gruvbox to the current version? There is possibility that you have an outdated one

**Comment by cassiomarques** [comment]
@morhetz Just did that, the latest commit I have is 273c030. The problem still persists, unfortunately :cry:

**Comment by morhetz** [comment]
Seems like that cold happen if you have environment variable TERM_ITALICS = true
So the easiest way to fix comments displaying is to enforce `let g:gruvbox_italic=0` at your `.vimrc` **before** `colorscheme gruvbox`
