### ISSUE TITLE
Bad background colors on sing gutter when using gruvbox + git-gutter

### ISSUE THREAD

**Issue by PaBLoX-CL** [morhetz/gruvbox#64]
I just updated all my vim plugins, and found a weird issue with gruvbox + git-gutter. I know it's not git-gutter fault because other colorschemes doesn't exhibit that problem:

![selection_036](https://cloud.githubusercontent.com/assets/275754/8026158/79568e84-0d42-11e5-8213-3b4a13f8a136.png)

I would have expected the background of the sign to be the same of the background of the writing area, not the same as the cursorline.

PS.- it also happens with gvim, so it's not a terminal issue :)

**Comment by PaBLoX-CL** [comment]
In case is useful:

```vim
:hi SignColumn
SignColumn     xxx term=standout ctermbg=237 guibg=#3c3836
                   links to LineNr
```

**Comment by morhetz** [comment]
Hi!
There's an option for this [g:gruvbox_sign_column](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_sign_column)
https://github.com/morhetz/gruvbox/issues/15#issuecomment-30093007

**Comment by amilsil** [comment]
For anyone landing here, settings `let g:gitgutter_override_sign_column_highlight=1` fixes the sign column for you.
![screen shot 2019-02-21 at 1 50 43 pm](https://user-images.githubusercontent.com/7359881/53140093-c45e3c00-35df-11e9-81e3-969613e23b15.png)

**Comment by baIIoon** [comment]
So sorry for bother you guys, @amilsil please tell me what font is it ? im falling in love

**Comment by koredefashokun** [comment]
@baIIoon It looks like Space Mono to me.
