### ISSUE TITLE
Spelling syntax highlight questions

### ISSUE THREAD

**Issue by ShengYun** [morhetz/gruvbox#65]
Currently the syntax highlighting for spelling works as below:

let g:gruvbox_improved_warnings=0

Terminal:
![screen shot 2015-06-16 at 3 36 20 pm](https://cloud.githubusercontent.com/assets/1317203/8192631/7d4cb4ee-143d-11e5-83c6-9a8e8d239efe.png)

macvim:
![screen shot 2015-06-16 at 3 36 07 pm](https://cloud.githubusercontent.com/assets/1317203/8192639/84082b74-143d-11e5-89a9-0d37ef068298.png)

It feels wrong since a bad spelling is more important than a not capitalised word, in other colorschemes, a bad spelling is usually marked as red and a not capitalised word is usually blue. And btw why does the behaviour of terminal and GUI differ? is there a bug?

jellybeans(terminal)
![screen shot 2015-06-16 at 3 40 12 pm](https://cloud.githubusercontent.com/assets/1317203/8192699/014b07d2-143e-11e5-8402-ef16e539c111.png)

jellybeans(GUI):
![screen shot 2015-06-16 at 3 40 17 pm](https://cloud.githubusercontent.com/assets/1317203/8192705/0e904d80-143e-11e5-8350-ae0edbb46643.png)

I read the documents and found there is an option called `g:gruvbox_improved_warnings`

I set it but the results went worse:
Terminal:
![screen shot 2015-06-16 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/1317203/8192733/42adc34a-143e-11e5-9f4c-4bce50117437.png)

GUI:
![screen shot 2015-06-16 at 3 42 30 pm](https://cloud.githubusercontent.com/assets/1317203/8192742/52435504-143e-11e5-96e8-531a8574be7e.png)

It made the not capitalised word more visible than a mis spelled word.

Could you change the colors of the spelling syntax?

Also `SyntasticError` is using red undercurl which in my opinion is great, so how about we change the color of mis spelled words and not capitalised words to the same as jellybeans?

**Comment by morhetz** [comment]
I believe PR #50 currently solves this problem
