### ISSUE TITLE
Additional syntax highlighting doesn't work in vim when using urxvt-256-xresources

### ISSUE THREAD

**Issue by ycny** [morhetz/gruvbox#68]
Hi
I was using gvim a lot, but decided to go with vim from now on. Gruvbox is perfect, but when writing in C, I need highlight functions as well (and I really don't like purple :P). I did this in gvim by doing:
in `.vim/bundle/gruvbox/colors/gruvbox.vim`
```
hi def cCustomFunc guifg=#fb4934                                                
65 hi def link cCustomClass Function
```
and in `.vim/syntax/c.vim`
```
syn match    cCustomParen    "?=(" contains=cParen,cCppParen
syn match    cCustomFunc     "\w\+\s*(\@=" contains=cCustomParen
syn match    cCustomScope    "::"
syn match    cCustomClass    "\w\+\s*::" contains=cCustomScope

```

This is working perfectly in gvim: 
![2015-07-15-092348_869x708_scrot](https://cloud.githubusercontent.com/assets/11892637/8693259/38c6922c-2ad6-11e5-91c5-622890951503.png)

but in Vim, launched from urxvt-256-xresources (using https://github.com/morhetz/gruvbox-generalized/blob/master/urxvt256/gruvbox-urxvt256.xresources) this sadly looks like this:

![2015-07-15-092321_893x648_scrot](https://cloud.githubusercontent.com/assets/11892637/8693320/9453dcee-2ad6-11e5-8891-509652b6c16d.png)

Is there any way to fix this?

**Comment by vdrandom** [comment]
> hi def cCustomFunc guifg=#fb4934
You also need ctermfg, vim does not automatically approximate the colour for terminal.

**Comment by ycny** [comment]
Damn, I knew I forgot about something simple. Thanks:)
