### ISSUE TITLE
colors off in nightly iTerm2 build

### ISSUE THREAD

**Issue by smutch** [morhetz/gruvbox#69]
After upgrading to iTerm2 nightly build (2.9.20150626 beta), the background colour in gruvbox appears darker than previously and there seems to be a larger contrast all round.

![screen shot](https://cloud.githubusercontent.com/assets/782987/8892041/972d6410-3384-11e5-8926-d6cb1f367ccb.png)

I'm using the same `gruvbox_256_palette_osx.sh` script as previously.  I guess this is something to do with the 24bit colour support which is the new iTerm2 builds?

**Comment by morhetz** [comment]
Hi, @smutch 
It seems like iTerm finally corrected ugly color profiles, so there is no need to use iterm-specific `gruvbox_256_palette_osx.sh`. Just replace it with `gruvbox_256_palette.sh` (no `-osx` postfix).

**Comment by smutch** [comment]
That seemed to do the trick.  :smiley:

**Comment by morhetz** [comment]
@smutch glad it worked, sorry for late answer anyway

**Comment by morhetz** [comment]
By the way, if you are using neovim you should definitely try it's [true color mode](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#0-recommended-nvim_tui_enable_true_color1) to drop shellscripts and other workarounds

**Comment by smutch** [comment]
No worries at all for the late reply. I used the soft contrast setting to tone things down a bit and was happily using that. I just gave the neovim true color mode a try though and it works perfectly. Thanks for the tip!
