### ISSUE TITLE
Gruvbox is breaking ctrlp while in tmux

### ISSUE THREAD

**Issue by jrock2004** [morhetz/gruvbox#71]
Been using your theme and I love it. The only problem I have is when I am in tmux and using your theme, I cannot use ctrlp. I can open it but the arrow keys are broken. If I disable your theme it works fine. Any ideas on what it could be?

**Comment by morhetz** [comment]
Whops, that's weird. I'll try to investigate that behaviour shortly.

**Comment by morhetz** [comment]
@jrock2004 Nope. Sorry, I can't reproduce that. Please provide additional info:
1. What's your TERM inside tmux (`echo $TERM`)?
2. What's the value of t_Co at vim inside tmux (`:echo &t_Co`)?
3. What's your tmux.conf?
4. What's your terminal emulator?
4. Can you reproduce that with clean vimrc without additional plugs and settings enabled, just gruvbox and ctrlp?

**Comment by jrock2004** [comment]
I figured the problem. I had to force tmux to start with 256 color by doing the following command:

```
tmux -2
```
