### ISSUE TITLE
String color in JSON confound with the background color.

### ISSUE THREAD

**Issue by towry** [morhetz/gruvbox#72]
<img width="253" alt="2015-09-04 1 41 04" src="https://cloud.githubusercontent.com/assets/8279858/9677322/21d5dd5e-530b-11e5-845f-96237b40dc0f.png">

The color is black, after type the second quote mark, the color will become a lighter color.

**Comment by morhetz** [comment]
Hi, @towry 
I've just released 2.0.0 version, which fixes this. Please update gruvbox

**Comment by towry** [comment]
Ok, thanks.

**Comment by bradenbest** [comment]
Wouldn't the poor contrast actually *help* the user spot a syntax error? Maybe it should highlight un-closed quotes with an ugly color.

**Comment by morhetz** [comment]
@bradenbest 
![Alt text](https://monosnap.com/file/JOvn10ELnzvW1ZSggiLif3u5Z1afmY.png)

**Comment by bradenbest** [comment]
Excellent!
