### ISSUE TITLE
deprecated var message forced to show even if it's not defined

### ISSUE THREAD

**Issue by mkarmona** [morhetz/gruvbox#73]
This [piece of code (if block)](https://github.com/morhetz/gruvbox/blob/7fde9c10ceff684529c1646bf759af3a25bb576c/colors/gruvbox.vim#L69) has to be rewritten as follows:

```VimL
if exists('g:gruvbox_contrast')
  echo 'g:gruvbox_contrast is deprecated; use g:gruvbox_contrast_light and g:gruvbox_contrast_dark instead'
endif
```

![captura de pantalla_2015-09-04_20-02-23](https://cloud.githubusercontent.com/assets/5394232/9692307/14b0a016-5340-11e5-915f-424060e2ba7d.png)

**Comment by morhetz** [comment]
It's weird, as it shouldn't be, but you for sure you're right. Thanks!

**Comment by mkarmona** [comment]
Thanks a lot! fixing speed level: wow...
