### ISSUE TITLE
Support truly black background

### ISSUE THREAD

**Issue by chrisl8** [morhetz/gruvbox#74]
On some of my devices the only background that is not difficult to read on is a truly black background.
I can accomplish this by adding `highlight Normal ctermbg=None` to my .vimric, however this causes the text in Airline to become bright red.

Can we have an option for a "true black" background that does not break the gruvbox AirLine theme?

**Comment by morhetz** [comment]
What do you mena by `truly black`, #000000?
There is hard contrast option which sets bg as #1d2021
What kind of devices is that?

**Comment by morhetz** [comment]
> `highlight Normal ctermbg=None`
It seems more suitable to use `highlight Normal ctermbg=0`

> this causes the text in Airline to become bright red
I can't reproduce that anyway. Please, specify more info: what device it is, what term emulator, what t_Co, tmux/screen in use, airline colorscheme, etc

**Comment by chrisl8** [comment]
Yes #000000
I have tried the "hard contrast" option, but the background is still "bright" and washes out the text on my laptop screen.

`highlight Normal ctermbg=0` does not set the background color to black, it is still a grey color.

This is in Ubuntu using the GNOME Terminal.
I am not using tmux.
I am using the gruvbox airline colorscheme, that is the one in which the text turns red.
set t_Co=256

If you run `highlight Normal ctermbg=None` inside vim, it will not affect AirLine until you run `AirlineRefresh`

**Comment by morhetz** [comment]
@chrisl8 That's issue related to airline's `get_highlight` methods parsing `None` value incorrectly
I'll try to provide fix to the airline, though you could easily override airline theme like that to hotfix the issue: https://gist.github.com/morhetz/8aaf5067cdf315d3aa7d

**Comment by chrisl8** [comment]
Thank you!
