### ISSUE TITLE
Globals not being picked up

### ISSUE THREAD

**Issue by FuzzOli87** [morhetz/gruvbox#79]
Hello,

Setting a global for this application is not getting picked up on Neovim. Something like 
let g:gruvbox_contrast_dark='hard' 

is not working.

I'm using iterm2-nightly and I built nvim from source earlier today. True colors are on for NVIM.

**Comment by morhetz** [comment]
Could you reproduce this at runtime?

    :let g:gruvbox_contrast_dark='hard' 
    :colo gruvbox

**Comment by hrangan** [comment]
I was getting the same problem. It worked for me if I set the contrast before setting the colorscheme
```
let g:gruvbox_contrast_dark='hard'
silent colorscheme gruvbox
```

**Comment by FuzzOli87** [comment]
Maybe something was off somewhere else but it now works like it should.

**Comment by dzintars** [comment]
I will report this as well. Same issue. @hrangan solution worked for me.
