### ISSUE TITLE
gruvbox partially disables other color schemes highlighting

### ISSUE THREAD

**Issue by pedjako** [morhetz/gruvbox#80]
If gruvbox is default colorscheme, and try to switch scheme(custom shortcut or command wise, it don't matter), syntax highlighting in new scheme(tried multiple new schemes) is partial only.

If gruvbox is not default colorscheme, same happens after switching to gruvbox, and then switching to another scheme afterwards.

If gruvbox is not used everything works ok.

![1](https://cloud.githubusercontent.com/assets/7421212/10499040/59e4db0e-72ce-11e5-96bc-06d0283b8830.png)
![2](https://cloud.githubusercontent.com/assets/7421212/10499041/59ed7854-72ce-11e5-9c85-9becc631ed69.png)
![3](https://cloud.githubusercontent.com/assets/7421212/10499042/59f4e300-72ce-11e5-83cc-0bcdcd1ef42d.png)

**Comment by morhetz** [comment]
Please refer that topic: http://stackoverflow.com/questions/12915797/gvim-remove-syntax-highlighting-groups
It's not gruvbox issue anyway
