### ISSUE TITLE
Colorscheme background issue when running in tmux

### ISSUE THREAD

**Issue by dmdque** [morhetz/gruvbox#81]
First, thanks for the great plugin! Now the issue: running vim with gruvbox in tmux doesn't look the way it should.

Here's gruvbox working fine, running on zsh on iterm2 on OSX:
<img width="911" alt="screen shot 2015-10-18 at 7 21 14 pm" src="https://cloud.githubusercontent.com/assets/5205766/10568590/25acfc50-75cf-11e5-85c5-ccf254246bb3.png">

Here it is running in tmux (Ran with a ~/.tmuxtest.conf containing only the line `set -g default-terminal "xterm-256color"`. Everything else about the environment is the same.):
<img width="912" alt="screen shot 2015-10-18 at 7 26 31 pm" src="https://cloud.githubusercontent.com/assets/5205766/10568594/32f24fb4-75cf-11e5-91b0-28bf75f28575.png">

As you can see, line backgrounds are grey, but become black after the end of every line. 

Here's some additional info:

        $ tmux -V
        tmux 2.0
        $ vim --version
        VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep  8 2015 20:13:59)
        MacOS X (unix) version
        Included patches: 1-826
        Compiled by Homebrew
        Huge version without GUI.  Features included (+) or not (-):
        +acl             +farsi           +mouse_netterm   +syntax
        +arabic          +file_in_path    +mouse_sgr       +tag_binary
        +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
        -balloon_eval    +float           +mouse_urxvt     -tag_any_white
        -browse          +folding         +mouse_xterm     -tcl
        ++builtin_terms  -footer          +multi_byte      +terminfo
        +byte_offset     +fork()          +multi_lang      +termresponse
        +cindent         -gettext         -mzscheme        +textobjects
        -clientserver    -hangul_input    +netbeans_intg   +title
        +clipboard       +iconv           +path_extra      -toolbar
        +cmdline_compl   +insert_expand   +perl            +user_commands
        +cmdline_hist    +jumplist        +persistent_undo +vertsplit
        +cmdline_info    +keymap          +postscript      +virtualedit
        +comments        +langmap         +printer         +visual
        +conceal         +libcall         +profile         +visualextra
        +cryptv          +linebreak       +python          +viminfo
        +cscope          +lispindent      -python3         +vreplace
        +cursorbind      +listcmds        +quickfix        +wildignore
        +cursorshape     +localmap        +reltime         +wildmenu
        +dialog_con      -lua             +rightleft       +windows
        +diff            +menu            +ruby            +writebackup
        +digraphs        +mksession       +scrollbind      -X11
        -dnd             +modify_fname    +signs           -xfontset
        -ebcdic          +mouse           +smartindent     -xim
        +emacs_tags      -mouseshape      -sniff           -xsmp
        +eval            +mouse_dec       +startuptime     -xterm_clipboard
        +ex_extra        -mouse_gpm       +statusline      -xterm_save
        +extra_search    -mouse_jsbterm   -sun_workshop    -xpm
           system vimrc file: "$VIM/vimrc"
             user vimrc file: "$HOME/.vimrc"
         2nd user vimrc file: "~/.vim/vimrc"
              user exrc file: "$HOME/.exrc"
          fall-back for $VIM: "/usr/local/share/vim"
        Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
        Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc

**Comment by magicalbanana** [comment]
Same here. Any fix for this?

**Comment by ScriptorNY** [comment]
Hello, I had the same problem. I searched for hours, and from [this post](https://superuser.com/questions/399296/256-color-support-for-vim-background-in-tmux) I found the solution. After testing several solutions, by just adding `set t_ut=` at the end of my `.vimrc` the problem was finally solved.

Hope, I helped

**Comment by magicalbanana** [comment]
Mine I set my terminal background to xterm-256 through my zshrc file because tmux apparently creates a new shell and disregards the color.

```
  export TERM=screen-256color
```

**Comment by ScriptorNY** [comment]
Thank you :) I also tried that but it didn't work for me, so that's why I ended up using this solution.
Thank you again :)

**Comment by dmdque** [comment]
Adding `set t_ut=` to my .vimrc fixed it for me. Thanks!
For anyone reading, that option is described as "clearing uses the current background color."

**Comment by polyzen** [comment]
Fwiw ncurses 6 includes tmux-256color. I've got this in my .tmux.conf 'set
-g default-terminal "tmux-256color"'

**Comment by jojoyuji** [comment]
Thx @ScriptorNY  '''set t_ut=''' worked for me too :) :+1:

**Comment by morhetz** [comment]
So, as I understood @ScriptorNY 's solution fixes that issue. Nice!
@dmdque @magicalbanana
Could this issue be closed as I document tmux integration issue (`set t_ut=`) at gruvbox wiki?

**Comment by magicalbanana** [comment]
Also the my solution. My issue wasn't localized to tmux, opening vim by default gave me the grayish background overylay but doing my setting fixed it.

**Comment by dmdque** [comment]
@morhetz Yes, adding it to the wiki works. Thanks!

**Comment by sunaku** [comment]
To be fair, @ScriptorNY's "solution" is really just [an unattributed reiteration](http://superuser.com/a/562423) of my `t_ut` discovery from 3 years ago, which you can [read about in detail here](http://sunaku.github.io/vim-256color-bce.html). :neckbeard: Cheers, and thanks for Gruvbox, @morhetz! :bow:

**Comment by ScriptorNY** [comment]
@sunaku, I'm really sorry. The "solution" I found was really just something I found on the web through my research. I had no intention of stealing someone else idea's or discovery. My only intention was to help other people as it did for me.

**Comment by magicalbanana** [comment]
@sunaku I tried your solution from your blog but didn't work. The only thing that works is my initial solution. :crying_cat_face:

**Comment by sunaku** [comment]
@ScriptorNY Thanks for clarifying. :+1:  I'm sure it was unintentional but I just wanted to be fair. :sweat_smile:

@magicalbanana I used to do the same thing until @tejr enlightened me about using `$TERM` strings properly [in this article](http://blog.sanctum.geek.nz/term-strings/).  There may be something more complex happening in your setup, so I hope that someday you get a chance to investigate further than relying on the `TERM=xterm-256color` override. :neckbeard:
