### ISSUE TITLE
Gray background?

### ISSUE THREAD

**Issue by magicalbanana** [morhetz/gruvbox#82]
It looks fine on almost all except I still have this grayish background and also not seeing comment highlighting.

What could be the cause of this?

Feel free to look at my city dotfiles.

https://github.com/magicalbanana/dotfiles

**Comment by magicalbanana** [comment]
I fixed this.

```
hi Normal ctermbg=none
hi NonText ctermbg=none
```

**Comment by polyzen** [comment]
Is this fixed upstream? This should probably still be open if not

**Comment by magicalbanana** [comment]
What do you mean upstream? I fixed this on my own. Just added those two lines on my vimrc and poof works. Although should I be expecting comment highlighting cause there's none but it's kewl for now.

**Comment by morhetz** [comment]
@magicalbanana could you provide screenshot, please?
As I understood that's related to #81, as you're probably using term with transparent background. Though I don't understand what do you mean by "not seeing comment highlighting".

**Comment by magicalbanana** [comment]
<img width="681" alt="screen shot 2015-10-27 at 10 29 07 am" src="https://cloud.githubusercontent.com/assets/7953984/10762825/97edde0c-7c95-11e5-8532-fcda37199632.png">

So the comment line should be highlighted right?

**Comment by morhetz** [comment]
@magicalbanana well it's highlighted with gray color, isn't it?
unrelated: you should probably try [color correction](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#2-colors-are-off).

**Comment by magicalbanana** [comment]
The color is gray yes but on the Gallery there's an additional highlight. But it's cool and yeah I already did the color correction.

**Comment by polyzen** [comment]
By upstream I mean gruvbox. As in, should those be added to
colors/gruvbox.vim somewhere?

**Comment by magicalbanana** [comment]
Probably? If this is a common behaviour issue then it should be a setting. I can make a PR if that would be easier.

**Comment by morhetz** [comment]
@magicalbanana 

> I can make a PR if that would be easier.

No worries, I'll fix it at #81 as I finish some tests

> on the Gallery there's an additional highlight

Well, not really, comments should be highlighted with gray color just a little bit warmer after you did color correction. [See example](https://camo.githubusercontent.com/2fcf604967167347f15ca8be125d32b18db9bc28/687474703a2f2f692e696d6775722e636f6d2f476b496c38466e2e706e67)

**Comment by magicalbanana** [comment]
@morhetz coolio. Great theme by the way. Thanks! Let me know if there's anything I can do. :dancer: :bee:
