### ISSUE TITLE
How to install gruvbox without using package managers.

### ISSUE THREAD

**Issue by timfayz** [morhetz/gruvbox#84]
Hello) I'm trying to install gruvbox without using any package managers. So the first I downloaded `colors/gruvbox.vim` file and place it under `~/.vim/colors`. After I just run `:colorscheme gruvbox` and get the following:
![screenshot from 2015-11-03 21 40 47](https://cloud.githubusercontent.com/assets/6209197/10917786/971559b8-8273-11e5-8271-26e787e1b4e6.png)

Is it possible to switch dark mode?

**Comment by wfxr** [comment]
set background=dark
If you want dark mode always, just add this in your vimrc file:)

**Comment by polyzen** [comment]
[Togglebg.vim](https://github.com/altercation/vim-colors-solarized/blob/master/autoload/togglebg.vim) also does the job. Bind it to F5 like [so](https://github.com/polyzen/dotfiles/blob/common/.vim/vimrc#L18).

You'll want to check out at least the "usage" and "terminal specific" pages of the [wiki](https://github.com/morhetz/gruvbox/wiki).

**Comment by timfayz** [comment]
> Togglebg.vim also does the job. Bind it to F5 like so.

@polyzen, for the moment I want to use only built-in features as much as possible. I'm really tired of a lot of bells and whistles)

> set background=dark

@wfxr, good, it works. What about contrast options (`g:gruvbox_contrast_dark`)? Or it is available only after installing plugin?

**Comment by morhetz** [comment]
@timfayz 
> What about contrast options (g:gruvbox_contrast_dark)? Or it is available only after installing plugin? 

Works as well

Please read docs first. Then ask questions.
1. [Usage](https://github.com/morhetz/gruvbox/wiki/Usage)
2. [Terminal specific](https://github.com/morhetz/gruvbox/wiki/Terminal-specific)

**Comment by timfayz** [comment]
@morhetz , I've already read these docs. I write here, because I didn't find answers to my questions. I think github create Issue section not just for *bugs*, but **issues**, don't you think so?

So adding `g:gruvbox_contrast_dark=hard` doesn't work. Vim says `Pattern not found: gruvbox_contrast_dark=hard`:

![screenshot from 2015-11-04 11 28 07](https://cloud.githubusercontent.com/assets/6209197/10933129/5185a6c2-82e7-11e5-949b-659441a91b1e.png)

Any ideas?

**Comment by timfayz** [comment]
@morhetz , I've already read these docs. I write here, because I didn't find answers to my questions. I think Github create Issues section not just for *bugs*, but **issues**, don't you think so?

So adding `let g:gruvbox_contrast_dark=hard` doesn't work. Vim gives errors:

![screenshot from 2015-11-04 11 31 59](https://cloud.githubusercontent.com/assets/6209197/10933188/b08acc06-82e7-11e5-86c5-54569b4c9ba2.png)

Any ideas?

**Comment by wfxr** [comment]
You missed the quotes. 
There is no need to use "g:gruvbox_contrast_dark" changing the color to dark. If you really want to do so and it still doesn't work, try to put this line before the color scheme setting statement(line 65). Maybe g:gruvbox_contrast_dark's value should be given before the color scheme being loaded.

**Comment by wfxr** [comment]
Which I mean this should work:
`let g:gruvbox_contrast_dark='hard'`
`colorscheme gruvbox`

**Comment by timfayz** [comment]
Great!))) You are right, I just missed the quotes. The order doesn't matter, it works before/after. Thank you sir!)

**Comment by wfxr** [comment]
You're welcome:)

**Comment by morhetz** [comment]
@timfayz 
Nope, sorry to say that, but you're wrong.

Question about switching bg mode was totally covered at (Usage section)[https://github.com/morhetz/gruvbox/wiki/Usage].
Question about contrast options wasn't really a question.
You got an **issue** with missed quotes, yes. I'm glad @wfxr was blazing fast to answer.
But next time please, do me a favor, read docs first.

**Comment by timfayz** [comment]
Never mind. Thank you for clarification. The problem (why I didn't understand the usage section) is there is no mention I can install it manually. For example, here is the list of available options to install gruvbox:

>
- Pathogen
  + `git clone https://github.com/morhetz/gruvbox.git ~/.vim/bundle/gruvbox`  
- Vundle
  + Add `Plugin 'morhetz/gruvbox'` to your .vimrc and run `:PluginInstall`
- NeoBundle
  + Add `NeoBundle 'morhetz/gruvbox'` to your .vimrc and run `:NeoBundleInstall`
- vim-plug
  + Add `Plug 'morhetz/gruvbox'` to your .vimrc and run `:PlugInstall`

If there is explanation for **Manual installation** or if you just mentioned it anywhere there. Instead there are explanation about complicated package managers. For newbies like me it is absolutely not obvious that I can install this theme manually and it will work properly. Yep, I do installation manually, but I didn't understand that the listed configuration options will be available as well as I can go further to read the next Usage section. It feels like I did something wrong)

**Comment by polyzen** [comment]
https://duckduckgo.com/?q=how+to+install+vim+plugin&ia=qa

**Comment by morhetz** [comment]
@timfayz 
There currently no manual installation instruction since it's totally not recommended.
Most vim plugins don't provide manual instruction and neither [vimawesome](http://vimawesome.com/plugin/fugitive-vim) does.
It's easier and more convenient to use plugin manager. Manual installation is more like obsolete practice present time.
