### ISSUE TITLE
Cannot find color scheme 'gruvbox'

### ISSUE THREAD

**Issue by chechoRP** [morhetz/gruvbox#85]
I don't know if this is an issue of gruvbox or Vundle, but I am getting an error `E185: Cannot find color scheme 'gruvbox'` . I have the line `Plugin 'morhetz/gruvbox'` in my `.vimrc` and if a dig into the `.vim/bundle/` folder I can see `gruvbox` on it. 

Does anyone have the same issue?

**Comment by chechoRP** [comment]
Nevermind, it was a Vundle issue. I needed to change the line `call vundle#begin()` with `call vundle#rc()` in my `.vimrc`. (Not sure why though)

**Comment by xconcept** [comment]
same thing happened to me and the above suggestion made no difference. I was able to fix my situation by creating a colors directory in my .vim directory
`mkdir ~/.vim/colors`
and then copying the gruvbox colors file to that directory
`cp ~/.vim/bundle/gruvbox/colors/gruvbox.vim ~/.vim/colors/`

**Comment by nicolassilvar** [comment]
the last one makes the error disappear, but the plugin still not working! I try the change to vundle#rc, it didnt make a difference

**Comment by nicolassilvar** [comment]
Look into this
https://bbs.archlinux.org/viewtopic.php?id=120325

In ~/.vimrc you should have
set t_Co=256
syntax on

This made it work

**Comment by tuntsov** [comment]
Thanks, Nicolass, it works for me!

**Comment by peg-idri** [comment]
if you use `Pathogen`,  `execute pathogen#infect()` should be ahead of `colorscheme gruvbox`

```
.vimrc:
execute pathogen#infect()
colorscheme gruvbox
```

**Comment by Totoch** [comment]
I just had the same problem with Vundle but none of the above solution worked.

What did work is put 'Plugin 'morhetz/gruvbox' as the last plugin to load.

Hope it helps.

**Comment by rheemix** [comment]
> I just had the same problem with Vundle but none of the above solution worked.
> 
> What did work is put 'Plugin 'morhetz/gruvbox' as the last plugin to load.
> 
> Hope it helps.

Thank you. This worked for me as well.

**Comment by n4hm3** [comment]
vundle of plug: You must first have Plugin 'morhetz/gruvbox' in your vimrc and then do PlugInstall or PluginInstall after that add colorscheme gruvbox to vimrc and :source .

**Comment by HabibulRahman** [comment]
I did the following to solve this problem(tried all of the above solutions):

added - _Plugin 'morhetz/gruvbox'_ as the last plugin in _~/.vimrc.bundle_ 
added - _set t_Co=256_ in my .vimrc file
created **autoload** and **colors** directory in ~/.vim
then copied the contents of **autoload** and **colors** from **gruvbox** directory( _~/.vim/bundle/gruvbox_ )
_cp -r ~/.vim/bundle/gruvbox/autoload ~/.vim/autoload_
_cp -r ~/.vim/bundle/gruvbox/colors ~/.vim/colors_
and finally **source .vimrc**

**Comment by jmembreno4194** [comment]
Actually.. the solution is that you have to make sure the colorscheme command is after the "Plug 'morhetz/gruvbox'"... I found out that if it goes before, it wont work

**Comment by gabrielbeauchemin** [comment]
I had this problem because I put "colorscheme gruvbox" in my plugins.vim that I souce in init.vim. If I put "colorscheme gruvbox" after the source line of plugins.vim, it works well :)

**Comment by sanp-w** [comment]
> I had this problem because I put "colorscheme gruvbox" in my plugins.vim that I souce in init.vim. If I put "colorscheme gruvbox" after the source line of plugins.vim, it works well :)

fine ! I use neovim and vim-plug to manage my plug. i hava the same problem and it works when i use your solution.

**Comment by bugkiller-damo** [comment]
> 实际上..解决方案是你必须确保colorscheme命令在“Plug 'morhetz/gruvbox'”之后......我发现如果它在之前，它将无法工作

thank you ,it's useful.

**Comment by rohanrkamath** [comment]
I was having the same issue. I am using vim-plug for the installations.
1. Make sure the `colorscheme gruvbox` comes after plug Calls.
2. Make sure you `call plug#end()` after plugging in your desired plugs, for this case `Plug 'morhetz/gruvbox'`.

These were some changes and errors I made and were fixed. Hope this helps you too!

**Comment by Miraclezhb** [comment]
> Actually.. the solution is that you have to make sure the colorscheme command is after the "Plug 'morhetz/gruvbox'"... I found out that if it goes before, it wont work

I have tried this way and it's helpful

**Comment by itsknk** [comment]
> same thing happened to me and the above suggestion made no difference. I was able to fix my situation by creating a colors directory in my .vim directory `mkdir ~/.vim/colors` and then copying the gruvbox colors file to that directory `cp ~/.vim/bundle/gruvbox/colors/gruvbox.vim ~/.vim/colors/`

This worked for me! Thank you :)

**Comment by ZXTube** [comment]
For me the solution was putting `call plug#end()` **above** `colorscheme gruvbox`
