### ISSUE TITLE
`center` word has always red background in .scss files 

### ISSUE THREAD

**Issue by timfayz** [morhetz/gruvbox#86]
Why word `center` look like error? Spell is off. Please, see the screen:

![screenshot from 2015-11-05 23 05 41](https://cloud.githubusercontent.com/assets/6209197/10980313/60cb458e-8412-11e5-9298-c875928b699c.png)

Any ideas?

**Comment by morhetz** [comment]
@timfayz 
Not sure what's the real reason. Could please you specify what syntax file are you using and/or provide your vim dotfiles?

<img width="934" alt="scss" src="https://cloud.githubusercontent.com/assets/554231/10981636/f7ff1e4c-8419-11e5-8fc6-579b8256b1f3.png">

You could also debug it by yourself by appending that snippet to your `vimrc`
```
nmap <leader>s :call <SID>SynStack()<CR>
function! <SID>SynStack()
   if !exists("*synstack")
      return
   endif
   echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```
And then press `<leader>s` at NORMAL mode with cursor placed at the specified word. Like this:

<img width="672" alt="kj" src="https://cloud.githubusercontent.com/assets/554231/10981817/fb516afe-841a-11e5-97f1-cc5cf0964a4f.png">

BTW, I'm using [vim-polyglot package](https://github.com/sheerun/vim-polyglot)

**Comment by morhetz** [comment]
Ahhh, now I see. It's detected as `cssDeprecated` class. You should install updated syntax files for scss from that [tpope's repo](https://github.com/tpope/vim-haml) if you aren't installing [polyglot language pack](https://github.com/sheerun/vim-polyglot)

P.S. It seems like your [colors are off](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#2-colors-are-off). You could refer wiki to correct terminal color palette to exact match the gui true-color version

**Comment by timfayz** [comment]
Thank you, installing polyglot solves the problem) 

Yeap, colors restricted by 256 palette. But I deal with it later))
