### ISSUE TITLE
Colours not displaying correctly 

### ISSUE THREAD

**Issue by jillesme** [morhetz/gruvbox#88]
Hi,

After seeing the gruvbox screenshots I knew I found the colour-scheme I wanted. I am using the [dracula](http://zenorocha.github.io/dracula-theme/iterm/) theme for iTerm2 and your colour-scheme. 

Of course I have set t_Co to 256 and read the wiki but my Vim looks like this now:

<img width="722" alt="screenshot 2015-11-11 09 42 31" src="https://cloud.githubusercontent.com/assets/2955483/11087238/fcf7dbb2-8858-11e5-8e94-3fae11ae8585.png">

As you can see it looks alright, but nothing like the example. 

Any ideas?

**Comment by vdrandom** [comment]
Terminal uses the degraded / approximated 256 colour scheme. If you want perfect match with the gui vim (TrueColor), you should run a compatible terminal and a patched vim / neovim (TrueColor is not supported in vim), or modify some of your terminal colours via one of those two included sh-scripts. Probably the osx one. Just try running it and see if it gets better.

Keep in mind that you'll  have to do it every time after you launch a new terminal, so it may be a good idea to add the said script to the shellrc.
