### ISSUE TITLE
Don't extra highlight tab symbols on current line

### ISSUE THREAD

**Issue by codepushr** [morhetz/gruvbox#89]
Hi,

is there a way to not hightlight the tab symbols on the current line? In my opinion this is too prominent, I would like to set it to be a little lighter than the grey background of the current line.

Right now it's the same color as the code, I guess.

![screen shot 2016-01-06 at 15 20 36](https://cloud.githubusercontent.com/assets/1425202/12144666/91e46072-b489-11e5-8ade-8a0642115dfe.png)

**Comment by wsdjeg** [comment]
it should be same as the line below or above

**Comment by morhetz** [comment]
seems like it can't be changed due to vim limitations
