### ISSUE TITLE
Add specific support for MiniBufExpl

### ISSUE THREAD

**Issue by greduan** [morhetz/gruvbox#9]
It would be cool if you could add specific support for the [MiniBufExpl](https://github.com/fholgado/minibufexpl.vim) plugin for Vim. :)

You might also want to start using this plugin instead of Vim's tabline. Which is apparently wrong to use it as such, a tab line: http://stackoverflow.com/a/103590/1622940

In any case you should try it out. It's better. ;)

P.S.: Assuming you're using the tabline from the images which seem to have a tabline there. :)

**Comment by morhetz** [comment]
Closing as this would probably never done
