### ISSUE TITLE
Active buffer tab background color

### ISSUE THREAD

**Issue by towry** [morhetz/gruvbox#90]
The current active buffer tab background color is confused

<img width="426" alt="2016-01-07 1 05 38" src="https://cloud.githubusercontent.com/assets/8279858/12162626/84c08fd6-b53f-11e5-90e3-331bf0aa5d88.png">

I always thought the bright one is the current, active tab, it's confusing.

So I modify the source to change it to like this:
<img width="352" alt="2016-01-07 1 05 49" src="https://cloud.githubusercontent.com/assets/8279858/12162652/eb2e1996-b53f-11e5-8da1-951d5f741838.png">

Now the bright one is the current.

**Comment by morhetz** [comment]
Hi @towry.
This issue was related to [vim-buftabline](https://github.com/ap/vim-buftabline) plugin which made some custom highlighting.
I've modified it to match the current gruvbox airline buftabline colors.

**Comment by towry** [comment]
Cool, it's better now :)

<img width="604" alt="2016-01-12 10 25 45" src="https://cloud.githubusercontent.com/assets/8279858/12252968/f0a4f130-b916-11e5-970c-ae96ff1b917e.png">
