### ISSUE TITLE
Change red color (lower saturation)

### ISSUE THREAD

**Issue by McSinyx** [morhetz/gruvbox#92]
I think that the red color is a bit too sharp. As it is used a lot (for function highlighting), I suggest it's saturation should be a bit lowered, e.g. the main red color should be something like `#CC3933`.

Thanks.

**Comment by thriveth** [comment]
I personally like the current one; it gives a levelof contrast that I find very nice, also for longer work sessions.

**Comment by McSinyx** [comment]
I think the current red(s) doesn't fit the other ones which are soft, sweet an vivid. I think it would be better if the red colors is less just plain red (`FF0000`, any one?), which make easier on eyes and looks better.

Sorry for my bad English BTW.
