### ISSUE TITLE
How to fix neovim true color support.

### ISSUE THREAD

**Issue by wsdjeg** [morhetz/gruvbox#94]
before this PR https://github.com/neovim/neovim/pull/4155
![2016-02-04 23-04-36](https://cloud.githubusercontent.com/assets/13142418/12818926/ca2e9170-cb93-11e5-881a-de72eeeb8203.png)
### AFTER ,THERE IS NO TRUE COLOR SUPPORT
![2016-02-04 23-04-55](https://cloud.githubusercontent.com/assets/13142418/12818939/e6a9a876-cb93-11e5-8e2d-2876d99f6699.png)

as the wiki says,we can do like this
Note: jellybeans and this molokai fork are known to work with true color even after the change . Colorschemes that don't work after this change should be fixed (they should set ctermfg/ctermbg and guifg/guibg, without checking has('gui_running'))

**Comment by wsdjeg** [comment]
after update neovim ,only airline has no color,I think something maybe wrong with airline
![2016-02-05 20-37-43](https://cloud.githubusercontent.com/assets/13142418/12846613/667250a8-cc48-11e5-8423-04c85dd7cf06.png)
@chrisbra do you use this colorscheme?

**Comment by chrisbra** [comment]
Have you updated your airline plugin?

**Comment by wsdjeg** [comment]
Sorry to bother you,this issue has gone.thank for your work
