### ISSUE TITLE
cterm values vs hex slightly off

### ISSUE THREAD

**Issue by acidjazz** [morhetz/gruvbox#95]
From my research it seems that a lot of hex values are not really matching their cterm values, which brought me [to this situation](https://github.com/macvim-dev/macvim/issues/241#issuecomment-183222559). here is the example I gave when I learned this

![image](https://cloud.githubusercontent.com/assets/967369/12972137/5d9b06ba-d057-11e5-984d-e0af20056dae.png)

If need be I can fork and try and match some of these colors a bit closer, or is there an easier solution?

**Comment by morhetz** [comment]
@acidjazz 
That's how it's supposed to work
cterms are just 256 color palette approximation, true colors are correct one
[Refer wiki please](https://github.com/morhetz/gruvbox/wiki/Terminal-specific#2-colors-are-off)

**Comment by acidjazz** [comment]
I see, so you started off w/ the hex/gui (true colors) to build the theme and then did your best w/ cterm values to match?

**Comment by morhetz** [comment]
Yep
