### ISSUE TITLE
Bad rendering of some punctuation chars on printer

### ISSUE THREAD

**Issue by hutou** [morhetz/gruvbox#97]
When printing syntax highlighted source code, some punctuation characters are **most of the time, but not always** rendered with a black background (dark theme) or a yellow background (light theme).
This problem does not appear if I change to, say Desert colorscheme, before printing.
Is this a known problem ?
Thanks

**Comment by morhetz** [comment]
I believe that's too obscure issue to investigate. Sorry for that
