### ISSUE TITLE
FiraMono + Airline + nvim?

### ISSUE THREAD

**Issue by PaBLoX-CL** [morhetz/gruvbox#99]
I'm just wondering how did you get airline play nice with Fira Sans Mono (screenshot in the readme)

**Comment by morhetz** [comment]
@PaBLoX-CL 
Oh, I forgot to mention. There is Fira Mono fork that already contains powerline symbols, [Fira Code](https://github.com/tonsky/FiraCode).

**Comment by PaBLoX-CL** [comment]
Next question then... which terminal are you using? :P

**Comment by morhetz** [comment]
@PaBLoX-CL iTerm2 Version 3 Beta

**Comment by PaBLoX-CL** [comment]
Oh, that font looked awesome, but doesn't work with any terminal I use. Guess I'll have to keep on with deja vu :P
